// Generated by scripts/build-ox-learning.py. Edit the approved templates or generator.
export function mount(host, {bootstrap,request,onAccessRefresh}) {
  host.innerHTML = '<div id="criminal-ox-preview"><header class="ox-header"></header><nav class="ox-nav" aria-label="OX 학습 메뉴"></nav><main class="ox-content"></main><footer class="ox-app-nav"></footer></div>';
  return (() => {
    const root = host.querySelector('#criminal-ox-preview');
    const data = bootstrap.catalog;
    const main = root.querySelector('main');
    const nav = root.querySelector('nav');
    const byId = new Map(data.questions.map(q => [q.id,q]));
    const chapters = new Map(data.chapters.map(c => [c.id,c]));
    const collections = new Map(data.collections.map(c => [c.id,c]));
    const esc = s => String(s ?? '').replace(/[&<>"']/g,c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const safeHtml = html => { const doc = new DOMParser().parseFromString(html || '','text/html'); const walk = n => n.nodeType===3 ? esc(n.textContent) : (n.nodeType===1 && n.tagName==='U' ? '<u>'+Array.from(n.childNodes).map(walk).join('')+'</u>' : Array.from(n.childNodes).map(walk).join('')); return Array.from(doc.body.childNodes).map(walk).join(''); };
    const attempts = bootstrap.progress.map(p=>({id:p.question_id,answer:p.answer,correct:p.correct,seed:true}));
    let todayCount=bootstrap.todayCount;
    const progress=new Map(bootstrap.progress.map(p=>[p.question_id,p]));
    const attemptCounts=new Map(Object.entries(bootstrap.attemptCounts || {}));
    const statistics=new Map(Object.entries(bootstrap.statistics || {}));
    const notes = new Map();
    const note = id => { if(!notes.has(id)) notes.set(id,{text:'',bookmark:false,mastered:false}); return notes.get(id); };
    const updateNote=n=>{if(n)notes.set(n.question_id,{text:n.memo || '',hasMemo:n.has_memo || !!n.memo,bookmark:n.bookmark,mastered:n.mastered_version===byId.get(n.question_id)?.version});};
    bootstrap.notes.forEach(updateNote);
    let pending=false;
    const errorMessages={question_changed:'문제가 수정되었습니다. 화면을 새로고침해주세요.',question_unavailable:'현재 공개 중인 문제가 아닙니다. 화면을 새로고침해주세요.',ox_not_registered:'OX 이용 등록이 해제되었습니다. 관리자에게 문의해주세요.',ox_disabled:'학습 서비스가 잠시 중지되었습니다.',unauthorized:'다시 로그인해주세요.'};
    async function persist(action,body) {
      pending=true;root.setAttribute('aria-busy','true');
      try{return await request(action,body);}finally{pending=false;root.removeAttribute('aria-busy');}
    }
    function showError(error){if(blockBookAccess(error))return;let node=root.querySelector('[data-ox-error]');if(!node){node=document.createElement('p');node.dataset.oxError='true';node.setAttribute('role','alert');main.prepend(node);}node.textContent=errorMessages[error.code] || '저장하지 못했습니다. 연결을 확인하고 다시 시도해주세요.';}
    let route='home', collection=(data.collections.find(c=>c.accessible!==false)?.id || 'criminal-law'), filter='복습 필요', allChapters=false, allWeak=false, session=null, origin='home';
    const design={palette:'blue',fontSize:19,newUser:false,category:'lecture'};
    const effective = () => design.newUser ? attempts.filter(a=>!a.seed) : attempts;
    const stats = id => { const p=progress.get(id), last=p?{id,answer:p.answer,correct:p.correct}:null, wrong=p?.wrong_count || 0; let label=wrong?(last.correct?'다시 맞힘':wrong>=3?'반복 오답':'복습 필요'):'';if(wrong&&note(id).mastered)label='복습 완료';return {last,wrong,label,priority:({'반복 오답':1,'복습 필요':2,'다시 맞힘':3,'복습 완료':4}[label]||5)}; };
    const reviews = () => data.questions.map(q=>({q,...stats(q.id)})).filter(s=>s.wrong).sort((a,b)=>a.priority-b.priority||b.wrong-a.wrong);
    const chapterStat = c => { const latest=new Map(); effective().filter(a=>byId.get(a.id).chapter_id===c.id).forEach(a=>latest.set(a.id,a)); const solved=latest.size, right=Array.from(latest.values()).filter(a=>a.correct).length; const accuracy=solved ? right/solved*100:null; const progress=c.question_count ? solved/c.question_count*100 : 0; const enough=c.question_count>0 && solved>=Math.min(5,c.question_count); const label=!enough?'데이터 부족':accuracy<50?'매우 취약':accuracy<70?'취약':accuracy<85?'주의':'양호'; return {c,solved,accuracy,progress,wrong:solved-right,label,rank:({'매우 취약':1,'취약':2,'주의':3,'양호':4,'데이터 부족':5}[label]),score:enough?(100-accuracy)*.7+(100-progress)*.3:0}; };
    const meter = (v,label,color='') => `<div class="ox-meter" role="progressbar" aria-label="${esc(label)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(v)}"><span style="width:${v}%;${color?'background:'+color:''}"></span></div>`;
    const button = (label,action,extra='',classes='') => `<button type="button" class="btn secondary ox-button ${classes}" data-action="${action}" ${extra}>${label}</button>`;
    function renderNav(){ const items=[['home','house','오늘'],['chapters','book-open','단원'],['review','rotate-ccw','오답노트'],['weak','chart-no-axes-combined','취약']]; nav.hidden=route==='quiz'||route==='entry'; nav.style.display=nav.hidden?'none':''; nav.innerHTML=items.map(([id,icon,label])=>`<button type="button" data-action="nav" data-ox-route="${id}" ${(route===id||(['bookmarks','chapter-complete'].includes(route)&&id==='chapters')||(route==='result'&&session?.chapterId&&id==='chapters'))?'aria-current="page"':''}><i data-lucide="${icon}" aria-hidden="true"></i>${label}</button>`).join(''); const titles={lecture:'인터넷 수강생',online:'온라인 관리반',offline:'오프라인 수강생'}; root.querySelector('.ox-header').innerHTML=route==='entry'?`<div class="ox-brand">론박스터디</div><small>${titles[design.category]}</small>`:`<button type="button" class="mini-btn ox-plain" data-action="nav" data-ox-route="entry">← 수강생 홈</button><div class="ox-brand"><span class="ox-mark">OX</span>형사법</div>`; const footer=root.querySelector('.ox-app-nav'); footer.style.display=route==='quiz'?'none':''; footer.innerHTML=({lecture:['홈','플래너','스터디카페','마이'],online:['홈','스터디카페','성적','마이'],offline:['홈','출석','외출','성적','마이']}[design.category]).map(l=>`<span>${l}</span>`).join(''); }
    function entry(){const due=reviews().filter(s=>s.label!=='복습 완료').length; const offline=design.category==='offline'; main.innerHTML=`<span class="ox-eyebrow">MY STUDY</span><h2>오늘도, 나의 속도로.</h2><p class="ox-sub">${offline?'출석부터 학습까지, 차근차근.':'공부를 시작할 준비가 되었나요?'}</p><section class="ox-existing"><div class="ox-row"><h3>${offline?'출석 · 외출':'온라인 스터디카페'}</h3><span class="ox-sub">기존 영역</span></div><p class="ox-sub">${offline?'기존 출석·외출 안내와 행동 영역':'내 공부 공간과 학습 타이머'}</p></section><section class="ox-card ox-hero"><div class="ox-row"><span style="font-size:12px;letter-spacing:1px">STUDY · OX</span><span style="font-size:12px">2,960문항</span></div><h3>형사법 OX</h3><p class="ox-sub">오늘 풀고, 다시 맞히고.<br>헷갈리는 지문을 확실한 정답으로.</p><div style="font-size:12px;margin:18px 0 4px">형법 · 수사·증거 · 공판${due?` / 복습 ${due}개`:''}</div>${button('형사법 OX 시작하기 →','nav','data-ox-route="home"','ox-wide')}</section><div class="ox-section"><h3>학습 바로가기</h3><p class="ox-sub">${design.category==='lecture'?'타이머 · 순공 랭킹 · 공지사항':'기존 학습 안내와 공지사항'}</p></div>`; }
function home() {
  const due = pendingReviewItems();
  const today = todayCount;
  const completed = isSessionComplete();
  const answered = session ? session.ids.filter((id, index) => session.answers[index]).length : 0;
  const continuing = session?.ids.length && !completed;
  main.innerHTML = `<h2>오늘 학습</h2>
    <section class="ox-card ox-hero">
      <div class="ox-row"><span></span><span class="ox-sub">오늘 ${today}문항 풀이</span></div>
      <h3>${completed ? '오늘 학습 완료' : continuing ? esc(session.label) : '오늘 학습할 단원'}</h3>
      <p class="ox-sub">${completed ? `${esc(session.label)} · ${session.ids.length}문항을 모두 풀었어요.` : continuing ? `${answered} / ${session.ids.length}문항 풀이` : `선택한 단원의 안 푼 문제를 ${chapterSetSize}문항씩 풀어요.`}</p>
      ${button(completed ? '학습 결과 보기' : continuing ? '학습 이어하기 →' : '단원 선택하고 시작 →', completed ? 'session-result' : continuing ? 'resume' : 'daily', '', 'ox-primary ox-wide')}
      ${completed || continuing ? button('다른 단원 선택', 'daily', '', 'ox-wide') : ''}
    </section>
    <button type="button" class="ox-review-shortcut" data-action="review-needed" ${due.length ? '' : 'disabled'}>
      <span>복습할 오답</span><span class="ox-review-shortcut-count"><strong>${due.length}</strong> 문항${due.length ? '<span aria-hidden="true">›</span>' : ''}</span>
    </button>`;
}

function isSessionComplete() {
  return !!session?.ids.length && session.ids.every((id, index) => !!session.answers[index]);
}

function showSessionResult() {
  if (!isSessionComplete()) return;
  session.index = session.ids.length;
  route = 'result';
  render();
}

// Inserted into the local preview module by build-local-preview.py.
let criminalLawPart = 'general';

function chapterView() {
  if(collections.get(collection)?.accessible===false){lockedBookView();return;}
  const isCriminalLaw = collection === 'criminal-law';
  const lawParts = [
    { id: 'general', label: '형법 총론', prefix: '형법총론' },
    { id: 'specific', label: '형법 각론', prefix: '형법각론' },
  ];
  const selectedPart = lawParts.find(part => part.id === criminalLawPart) || lawParts[0];
  const list = data.chapters.filter(c => c.collection_id === collection
    && (!isCriminalLaw || String(c.part_title || '').replace(/\s/g, '').startsWith(selectedPart.prefix)));
  const scopeLabel = isCriminalLaw ? selectedPart.label : collections.get(collection).scope;
  const count = list.reduce((sum, c) => sum + c.question_count, 0);
  const visible = allChapters ? list : list.slice(0, 8);
  const short = ['형법', '수사·증거', '공판'];
  main.innerHTML = `
    <div class="ox-page-heading"><h2>단원 학습</h2><button type="button" class="ox-set-size-trigger" data-action="chapter-size" aria-haspopup="dialog">한 번에 ${chapterSetSize}문항 <span aria-hidden="true">⌄</span></button></div>
    ${bookTabs()}
    ${isCriminalLaw ? `<div class="ox-law-filters" role="group" aria-label="형법 학습 범위">
      ${lawParts.map(part => `<button type="button" class="ox-law-filter" aria-pressed="${part.id === selectedPart.id}" data-action="law-part" data-part="${part.id}">${part.label}</button>`).join('')}
    </div>` : ''}
    <section class="ox-chapter-panel" aria-label="${esc(scopeLabel)} 단원 목록">
      <header class="ox-chapter-head">
        <h3>${esc(scopeLabel)}</h3>
        <span class="ox-sub">${list.length}단원 · ${count.toLocaleString()}문항</span>
      </header>
      <div class="ox-chapter-list">
        ${visible.map(c => {
          const s = chapterCompletion(c);
          return `<button type="button" class="ox-chapter" data-action="chapter" data-id="${c.id}">
            <span class="ox-chapter-index">${String(c.sort_order).padStart(2, '0')}</span>
            <span class="ox-chapter-body">
              <strong>${esc(c.display_name)}</strong>
              <span class="ox-chapter-meta"><span>${c.question_count}문항</span><span class="${s.solved ? 'ox-chapter-started' : ''}">${s.complete ? `1회독 완료 · 정답률 ${Math.round(s.accuracy)}%` : s.solved ? `${s.solved}문항 학습` : '미학습'}</span></span>
              ${meter(s.progress, '단원 학습률')}
            </span>
            <span class="ox-chapter-chevron" aria-hidden="true">›</span>
          </button>`;
        }).join('')}
      </div>
      ${list.length > 8 ? `<div class="ox-chapter-bottom"><button type="button" class="ox-chapter-more" data-action="expand-chapters">${allChapters ? '단원 접기' : `전체 ${list.length}개 단원 보기`}<span aria-hidden="true">${allChapters ? '−' : '+'}</span></button></div>` : ''}
    </section>`;
}

function start(ids, label, options = {}) {
  if (!ids.length) return;
  if (['home', 'chapters', 'bookmarks', 'review', 'weak'].includes(route)) origin = route;
  else if (route === 'chapter-complete' || (route === 'result' && options.chapterId)) origin = 'chapters';
  session = { ids: [...new Set(ids)], index: 0, answers: [], label, chapterId: options.chapterId || null,
    chapterMode: options.chapterMode || 'learn', chapterRemaining: [...(options.chapterRemaining || [])] };
  route = 'quiz';
  render();
}

    function daily(){ route='chapters'; render(); }
let activeChapterId = null;
const CHAPTER_SET_SIZES = [10, 15, 20];
let chapterSetSize = 10;

function showChapterSizePicker() {
  if (root.querySelector('.ox-set-size-dialog')) return;
  const trigger = root.querySelector('[data-action="chapter-size"]');
  const dialog = document.createElement('dialog');
  dialog.className = 'ox-set-size-dialog';
  dialog.setAttribute('aria-labelledby', 'ox-set-size-title');
  dialog.setAttribute('aria-describedby', 'ox-set-size-description');
  dialog.innerHTML = `<h2 id="ox-set-size-title">한 번에 풀 문항 수</h2>
    <p id="ox-set-size-description" class="ox-sub">단원 학습에서 풀 문항 수를 선택해주세요.</p>
    <div class="ox-set-size-options" role="group" aria-label="문항 수">
      ${CHAPTER_SET_SIZES.map(size => `<button type="button" data-chapter-size="${size}" aria-pressed="${size === chapterSetSize}" ${size === chapterSetSize ? 'autofocus' : ''}>${size}문항</button>`).join('')}
    </div>
    <button type="button" class="ox-set-size-close">닫기</button>`;
  dialog.addEventListener('click', event => {
    const option = event.target.closest('button[data-chapter-size]');
    if (option) {
      const size = Number(option.dataset.chapterSize);
      if (!CHAPTER_SET_SIZES.includes(size)) return;
      chapterSetSize = size;
      trigger.innerHTML = `한 번에 ${chapterSetSize}문항 <span aria-hidden="true">⌄</span>`;
      dialog.close();
    } else if (event.target.closest('.ox-set-size-close')) {
      dialog.close();
    } else if (event.target === dialog) {
      const bounds = dialog.getBoundingClientRect();
      if (event.clientX < bounds.left || event.clientX > bounds.right
          || event.clientY < bounds.top || event.clientY > bounds.bottom) dialog.close();
    }
  });
  dialog.addEventListener('close', () => {
    dialog.remove();
    if (trigger.isConnected) trigger.focus();
  }, { once: true });
  root.append(dialog);
  dialog.showModal();
}

function chapterQuestions(id) {
  return data.questions.filter(q => q.chapter_id === id).sort((a, b) =>
    Number(a.source_question_number) - Number(b.source_question_number)
    || String(a.source_option_label || '').localeCompare(String(b.source_option_label || ''), 'ko'));
}

function shuffleQuestionIds(ids) {
  const shuffled = [...ids];
  // Shuffle the entire eligible chapter before splitting it into study sets.
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

function chapterCompletion(c) {
  const s = chapterStat(c);
  const questions = chapterQuestions(c.id);
  const wrong = questions.filter(q => {
    const last = stats(q.id).last;
    return last && !last.correct;
  });
  return { ...s, questions, wrong, complete: c.question_count > 0 && questions.length === c.question_count && s.solved === c.question_count };
}

function nextChapter(c) {
  const ordered = data.chapters.filter(item => item.collection_id === c.collection_id).sort((a, b) => a.sort_order - b.sort_order);
  return ordered[ordered.findIndex(item => item.id === c.id) + 1] || null;
}

function selectChapterScope(c) {
  collection = c.collection_id;
  if (collection === 'criminal-law') criminalLawPart = String(c.part_title).replace(/\s/g, '').startsWith('형법각론') ? 'specific' : 'general';
}

function startChapter(id, mode = 'learn') {
  const c = chapters.get(id);
  if (!c) return;
  activeChapterId = id;
  selectChapterScope(c);
  const s = chapterCompletion(c);
  if (mode === 'learn' && s.complete) {
    route = 'chapter-complete';
    render();
    return;
  }
  const questions = mode === 'wrong' ? s.wrong : mode === 'all' ? s.questions : s.questions.filter(q => !stats(q.id).last);
  // A sampled chapter may have no unseen items; it is still not fully completed.
  const selected = questions.length || mode === 'wrong' ? questions : s.questions;
  startChapterSet(c, shuffleQuestionIds(selected.map(q => q.id)), mode);
}

function startChapterSet(c, ids, mode) {
  start(ids.slice(0, chapterSetSize), c.display_name, {
    chapterId: c.id, chapterMode: mode, chapterRemaining: ids.slice(chapterSetSize),
  });
}

function remainingChapterIds() {
  return session.chapterRemaining.filter(id => byId.has(id)
    && (session.chapterMode === 'all' || (session.chapterMode === 'wrong'
      ? stats(id).last && !stats(id).last.correct : !stats(id).last)));
}

function continueChapterSet() {
  const c = chapters.get(session?.chapterId);
  if (!c) return;
  startChapterSet(c, remainingChapterIds(), session.chapterMode);
}

function chapterSessionResult() {
  const c = chapters.get(session.chapterId);
  if (!c) { chapterView(); return; }
  const s = chapterCompletion(c);
  const remaining = remainingChapterIds();
  if (!remaining.length && s.complete) {
    activeChapterId = c.id;
    chapterCompletionView();
    return;
  }
  const right = session.answers.filter(a => a.correct).length;
  main.innerHTML = `<section class="ox-completion">
    <p class="ox-sub">${esc(c.display_name)}</p>
    <h2>${session.ids.length}문항 학습 완료</h2>
    <div class="ox-completion-score"><span>이번 학습 정답</span><strong>${right}<small> / ${session.ids.length}</small></strong></div>
    <p class="ox-sub">단원 진도 ${s.solved} / ${c.question_count}문항</p>
    <div class="ox-completion-actions">
      ${remaining.length ? button(`다음 ${Math.min(chapterSetSize, remaining.length)}문항 풀기`, 'chapter-continue', '', 'ox-primary ox-wide')
        : button('이어서 학습하기', 'chapter', `data-id="${c.id}"`, 'ox-primary ox-wide')}
      ${button('단원 목록으로', 'nav', 'data-ox-route="chapters"', 'ox-wide')}
    </div>
  </section>`;
}

function chapterCompletionView() {
  const c = chapters.get(activeChapterId);
  if (!c) { chapterView(); return; }
  const s = chapterCompletion(c);
  if (!s.complete) { chapterView(); return; }
  const next = nextChapter(c);
  const nextButton = (primary) => next
    ? button('다음 단원 학습하기', 'chapter-next', `data-id="${next.id}"`, `${primary ? 'ox-primary ' : ''}ox-wide`)
    : button('다른 단원 선택하기', 'nav', 'data-ox-route="chapters"', `${primary ? 'ox-primary ' : ''}ox-wide`);
  main.innerHTML = `<section class="ox-completion">
    <p class="ox-sub">${esc(c.display_name)}</p>
    <h2>1회독 완료</h2>
    <p class="ox-sub">${s.solved} / ${c.question_count}문항 학습</p>
    <div class="ox-completion-score"><span>정답률</span><strong>${Math.round(s.accuracy)}<small>%</small></strong></div>
    <div class="ox-completion-wrong"><span>남은 오답</span><strong>${s.wrong.length}문항</strong></div>
    <div class="ox-completion-actions">
      ${s.wrong.length ? button('오답만 다시 풀기', 'chapter-wrong', `data-id="${c.id}"`, 'ox-primary ox-wide') : ''}
      ${nextButton(!s.wrong.length)}
      ${button(`${chapterSetSize}문항씩 다시 풀기`, 'chapter-restart', `data-id="${c.id}"`, 'ox-wide')}
    </div>
    ${next ? `<p class="ox-completion-next">다음 · ${esc(next.display_name)}</p>` : ''}
  </section>
  ${button('단원 목록으로', 'nav', 'data-ox-route="chapters"', 'ox-wide')}`;
}



function questionPresentation(q) { return {prompt:q.prompt,context:q.context}; }

function bookmarkedQuestions() {
  return data.questions.filter(q => notes.get(q.id)?.bookmark);
}

function bookmarkView() {
  const saved = bookmarkedQuestions();
  main.innerHTML = `
    <div class="ox-page-heading"><h2>북마크</h2>${button('단원으로', 'nav', 'data-ox-route="chapters"')}</div>
    <section class="ox-review-panel" aria-label="북마크한 문제">
      <header class="ox-review-head">
        <h3>저장한 문제 <span class="ox-review-count">${saved.length}문항</span></h3>
        ${saved.length ? button('모아 풀기', 'bookmarks-all', '', 'ox-primary') : ''}
      </header>
      ${saved.length ? saved.map(q => `<article class="ox-review-item">
        <p class="ox-source">${esc(chapters.get(q.chapter_id).display_name)}</p>
        <p class="ox-short-prompt">${esc(questionPresentation(q).prompt)}</p>
        <div class="ox-review-actions">
          ${button('풀기', 'one', `data-id="${q.id}"`, 'ox-primary')}
          ${button('북마크 해제', 'bookmark', `data-id="${q.id}"`)}
        </div>
      </article>`).join('') : `<div class="ox-review-empty"><h3>북마크한 문제가 없어요.</h3><p class="ox-sub">문제 화면의 ☆ 북마크를 눌러 저장해요.</p>${button('단원 골라 풀기', 'nav', 'data-ox-route="chapters"', 'ox-wide')}</div>`}
    </section>`;
}

function questionStatsMarkup(q) {
  const sample=statistics.get(q.id);
  const value=sample && sample.answered>=10?`${Math.round(sample.wrong/sample.answered*100)}%`:'집계 중';
  return `<div class="ox-question-stats"><div class="ox-question-stats-heading"><span>전체 수강생 오답률</span><strong>${value}</strong></div></div>`;
}

function quiz() {
  const q = byId.get(session.ids[session.index]);
  const display = questionPresentation(q);
  const c = chapters.get(q.chapter_id), a = session.answers[session.index], n = note(q.id);
  const pencilPath = a?.correct
    ? 'M53 13 C37 5 19 14 13 31 C6 49 17 66 34 69 C52 73 67 59 69 42 C71 26 61 13 47 11 C35 8 23 15 18 24'
    : 'M19 65 C29 52 41 41 49 30 C54 23 58 19 62 15';
  const pencilFilter = `ox-pencil-${a?.correct ? 'circle' : 'slash'}`;
  main.innerHTML = `<div class="ox-quiz">
    <div class="ox-quiz-toolbar">
      <button type="button" class="ox-quiz-tool" data-action="leave">← 나가기</button>
      <span class="ox-quiz-count"><strong>${session.index + 1}</strong> / ${session.ids.length}</span>
    </div>
    ${meter((session.index + (a ? 1 : 0)) / session.ids.length * 100, '세트 진행률')}
    <section class="ox-quiz-paper${a ? ' ox-graded' : ''}" aria-label="문제와 해설">
      <header class="ox-quiz-heading">
        <h3>${esc(c.display_name)}</h3>
        <button type="button" class="ox-quiz-tool ox-quiz-bookmark" data-action="bookmark" data-id="${q.id}" aria-label="${n.bookmark ? '현재 문제 북마크 해제' : '현재 문제 북마크 저장'}" aria-pressed="${n.bookmark}">${n.bookmark ? '★ 저장됨' : '☆ 북마크'}</button>
      </header>
      ${display.context ? `<div class="ox-context"><p>${esc(display.context)}</p></div>` : ''}
      <div class="ox-question">
      ${esc(display.prompt)}
      ${a ? `<svg class="ox-grade-mark" viewBox="0 0 80 80" aria-hidden="true" focusable="false">
        <defs>
          <filter id="${pencilFilter}" x="-15%" y="-15%" width="130%" height="130%" color-interpolation-filters="sRGB">
            <feTurbulence type="fractalNoise" baseFrequency=".85" numOctaves="3" seed="12" result="grain" />
            <feColorMatrix in="grain" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1.8 -.35" result="pencil-grain" />
            <feComposite in="SourceGraphic" in2="pencil-grain" operator="in" />
          </filter>
        </defs>
        <g filter="url(#${pencilFilter})">
          <path d="${pencilPath}" stroke-width="5.4" opacity=".85" />
          <path d="${pencilPath}" transform="translate(-1 .8)" stroke-width="2" opacity=".7" />
          <path d="${pencilPath}" transform="translate(1.2 -.6)" stroke-width="1.2" opacity=".65" />
        </g>
      </svg>` : ''}
      </div>
      <div class="ox-answer-grid">
        ${['O', 'X'].map(v => `<button type="button" class="btn secondary ox-answer ${a && a.answer === v ? 'ox-selected' : ''}" data-action="answer" data-answer="${v}" ${a ? 'disabled' : ''} aria-label="${v}: ${v === 'O' ? '옳다' : '틀리다'}"><span class="ox-answer-symbol ox-symbol-${v.toLowerCase()}" aria-hidden="true"></span></button>`).join('')}
      </div>
      <div aria-live="polite">
        ${a ? `<section class="ox-quiz-feedback">
          <div class="ox-grade-result">
            <div class="ox-grade-copy"><h3 class="${a.correct ? 'ox-correct' : 'ox-incorrect'}">${a.correct ? '정답이에요' : '오답이에요'}</h3><span class="ox-sub">정답 ${q.correct_answer}</span></div>
          </div>
          <div class="ox-explanation">${safeHtml(q.explanation_html)}</div>
          ${questionStatsMarkup(q)}
          <details><summary>나만의 메모 ${n.text ? '· 작성됨' : ''}</summary><textarea id="ox-memo" class="ox-note" rows="3" aria-label="나만의 메모">${esc(n.text)}</textarea>${button('메모 저장', 'memo', `data-id="${q.id}"`)}<div id="ox-message" class="ox-live" role="status"></div></details>
        </section>` : '<p class="ox-quiz-hint">답을 선택하면 해설을 확인할 수 있어요.</p>'}
      </div>
    </section>
    ${a ? button(session.index === session.ids.length - 1 ? '학습 결과 보기' : '다음 문제 →', 'next', '', 'ox-primary ox-wide') : ''}
  </div>`;
}

    function result(){if(session.chapterId){chapterSessionResult();return;}const right=session.answers.filter(a=>a.correct).length, wrong=session.answers.filter(a=>!a.correct).map(a=>a.id); main.innerHTML=`<div class="ox-result"><span class="ox-eyebrow">SESSION COMPLETE</span><h2>학습 결과</h2><p class="ox-sub">${esc(session.label)}</p><div class="ox-number">${right}<small> / ${session.ids.length} 정답</small></div><p class="ox-sub">${wrong.length?`다시 살펴볼 ${wrong.length}개 지문을 오답노트에 모았어요.`:'이번 세트는 모두 맞혔어요.'}</p></div><div class="ox-card"><h3>다음 학습</h3><p class="ox-sub">${wrong.length?'방금 틀린 지문을 다시 읽으면 차이를 더 쉽게 기억할 수 있어요.':'복습 완료로 표시해도 오답 이력은 유지돼요.'}</p>${wrong.length?button('방금 틀린 문제 다시 풀기','retry-session','','ox-primary ox-wide'):button('오답노트 확인하기','nav','data-ox-route="review"','ox-primary ox-wide')}${button('오늘 화면으로','nav','data-ox-route="home"','ox-wide')}</div>`; }
// Inserted into the local preview module by build-local-preview.py.
let reviewMode = 'pending', reviewChapterId = null, reviewStatus = 'all', reviewRepeated = false;

function openReview(mode = 'pending', chapterId = null) {
  if (chapterId && !chapters.has(chapterId)) return;
  reviewMode = mode === 'history' ? 'history' : 'pending';
  reviewChapterId = chapterId;
  reviewStatus = 'all';
  reviewRepeated = false;
  route = 'review';
}

function pendingReviewItems() {
  return reviews().filter(s => ['반복 오답', '복습 필요'].includes(s.label));
}

function reviewItemsForFilter() {
  return reviews().filter(s => {
    if (reviewChapterId && s.q.chapter_id !== reviewChapterId) return false;
    if (reviewMode !== 'history') return !note(s.q.id).mastered;
    if (reviewRepeated && s.wrong < 3) return false;
    return reviewStatus === 'all' || (reviewStatus === 'wrong' ? !s.last?.correct : !!s.last?.correct);
  });
}

function reviewItemMarkup(s) {
  const q = s.q, n = note(q.id);
  const display = questionPresentation(q);
  return `<article class="ox-review-item" data-review-question="${esc(q.id)}">
    <div class="ox-review-meta">
      <p class="ox-source">${esc(chapters.get(q.chapter_id).display_name)}</p>
      <span class="ox-sub">누적 ${s.wrong}회 오답</span>
    </div>
    <p class="ox-short-prompt">${esc(display.prompt)}</p>
    <div class="ox-history-badges"><span class="ox-badge">${s.last?.correct ? '다시 맞힘' : '아직 틀림'}</span>${s.wrong >= 3 ? '<span class="ox-badge ox-danger">반복 오답</span>' : ''}${n.mastered ? '<span class="ox-badge">복습 완료</span>' : ''}</div>
    <details data-question-detail="${q.id}">
      <summary>정답 · 해설 · 메모 보기</summary>
      <p class="ox-sub">정답 ${q.correct_answer}</p>
      ${display.context ? `<div class="ox-context">${esc(display.context)}</div>` : ''}
      <div class="ox-explanation">${safeHtml(q.explanation_html)}</div>
      ${questionStatsMarkup(q)}
      <p class="ox-sub">메모: ${esc(n.text) || '작성한 메모가 없어요.'}</p>
      <p class="ox-sub">북마크: ${n.bookmark ? '저장됨' : '저장하지 않음'}</p>
    </details>
    <div class="ox-review-actions">
      ${button('다시 풀기', 'one', `data-id="${q.id}"`, 'ox-primary')}
      ${button(n.mastered ? '완료 취소' : '복습 완료', 'master', `data-id="${q.id}"`)}
    </div>
  </article>`;
}

function review() {
  const visible = reviewItemsForFilter();
  const history = reviewMode === 'history';
  const all = reviews().filter(s => !reviewChapterId || s.q.chapter_id === reviewChapterId);
  const statusOptions = [['all', '전체 이력', all.length], ['wrong', '아직 틀림', all.filter(s => !s.last?.correct).length], ['regained', '다시 맞힘', all.filter(s => s.last?.correct).length]];
  main.innerHTML = `
    ${reviewChapterId ? button('취약단원으로', 'nav', 'data-ox-route="weak"') : ''}
    <h2>${reviewChapterId ? esc(chapters.get(reviewChapterId).display_name) : '오답노트'}</h2>
    ${reviewChapterId ? `<p class="ox-sub">이전 오답 · 복습 완료한 문항 포함</p>${button('전체 단원 이력 보기', 'review-mode', 'data-mode="history"')}` : `<div class="ox-history-tabs" role="group" aria-label="오답노트 보기"><button type="button" class="mini-btn ox-filter" data-action="review-mode" data-mode="pending" aria-pressed="${!history}">복습 목록</button><button type="button" class="mini-btn ox-filter" data-action="review-mode" data-mode="history" aria-pressed="${history}">전체 이력</button></div>`}
    ${history ? `<div class="ox-history-filters" role="group" aria-label="오답 이력 상태">${statusOptions.map(([value, label, count]) => `<button type="button" class="mini-btn ox-filter" data-action="history-status" data-status="${value}" aria-pressed="${reviewStatus === value}">${label} ${count}</button>`).join('')}<button type="button" class="mini-btn ox-filter" data-action="history-repeat" aria-pressed="${reviewRepeated}">반복 오답만</button></div>` : ''}
    <p class="ox-sub">복습 완료로 표시해도 오답 이력은 유지돼요.</p>
    <section class="ox-review-panel" aria-label="오답노트 문항">
      <header class="ox-review-head">
        <h3>${history ? '오답 이력' : '복습 목록'}<span class="ox-review-count">${visible.length}문항</span></h3>
        ${visible.length ? button('모아 풀기', 'review-all', '', 'ox-primary') : ''}
      </header>
      ${visible.length ? visible.map(reviewItemMarkup).join('') : `<div class="ox-review-empty">
        <h3>${history ? '조건에 맞는 오답 이력이 없어요.' : '복습 목록에 남은 문항이 없어요.'}</h3>
        <p class="ox-sub">${history ? '전체 이력이나 다른 조건에서 확인해 보세요.' : '복습 완료한 문항은 전체 이력에서 확인할 수 있어요.'}</p>
        ${button('단원 골라 풀기', 'nav', 'data-ox-route="chapters"', 'ox-wide')}
      </div>`}
    </section>`;
}

function weaknessStats() {
  const history = new Map();
  for (const q of data.questions) {
    const s = stats(q.id);
    if (!history.has(q.chapter_id)) history.set(q.chapter_id, { past: 0, regained: 0, repeated: 0, totalAttempts: 0, totalCorrect: 0, totalWrong: 0 });
    const item = history.get(q.chapter_id);
    const counts = questionAttemptCounts(q.id);
    item.totalAttempts += counts.attempts;
    item.totalCorrect += counts.correct;
    item.totalWrong += counts.wrong;
    if (!s.wrong) continue;
    item.past++;
    if (s.last?.correct) item.regained++;
    if (s.wrong >= 3) item.repeated++;
  }
  return data.chapters.map((c, index) => {
    const s = chapterStat(c), h = history.get(c.id) || { past: 0, regained: 0, repeated: 0, totalAttempts: 0, totalCorrect: 0, totalWrong: 0 };
    return { ...s, ...h, index, cumulativeAccuracy: h.totalAttempts ? h.totalCorrect / h.totalAttempts * 100 : null };
  });
}

function weaknessHistoryOrder(a, b) {
  return (a.cumulativeAccuracy ?? Infinity) - (b.cumulativeAccuracy ?? Infinity) || b.totalWrong - a.totalWrong || a.index - b.index;
}

function questionAttemptCounts(id) { return attemptCounts.get(id) || {attempts:0,correct:0,wrong:0}; }

function cumulativeAccuracyLabel(s) {
  if (s.cumulativeAccuracy === null) return '—';
  // Never round a record containing a wrong answer up to a perfect score.
  const rate = Math.min(s.totalWrong ? 99.9 : 100, Math.round(s.cumulativeAccuracy * 10) / 10);
  return `${rate}%`;
}

function weaknessRow(s) {
  const tone = s.past ? (s.wrong ? 'weak' : 'good') : 'pending';
  const status = s.past ? (s.wrong ? '복습 필요' : '다시 맞힘') : s.solved ? '오답 없음' : '미학습';
  return `<details class="ox-weak-row" data-weak-chapter="${esc(s.c.id)}">
    <summary>
      <span class="ox-weak-name">${esc(s.c.display_name)}</span>
      <strong class="ox-weak-rate">${cumulativeAccuracyLabel(s)}</strong>
      <span class="ox-weak-status ox-weak-${tone}">${status}</span>
      <span class="ox-weak-chevron" aria-hidden="true">⌄</span>
      <span class="ox-weak-history-summary">${s.past ? `이전 오답 ${s.past}문항 · 남은 오답 ${s.wrong}문항` : s.solved ? `${s.solved}문항 학습 · 틀린 문항 없음` : '아직 학습한 문항이 없어요.'}</span>
    </summary>
    <div class="ox-weak-detail">
      <p class="ox-sub">${esc(collections.get(s.c.collection_id).name)} · ${s.solved} / ${s.c.question_count}문항 학습</p>
      <p class="ox-sub">누적 ${s.totalAttempts}회 풀이 · 정답 ${s.totalCorrect}회 · 오답 ${s.totalWrong}회</p>
      <p class="ox-sub">${s.solved}문항 중 ${s.past}문항을 틀린 적이 있어요.${s.past ? ` 다시 맞힌 문항은 ${s.regained}문항이에요.` : ''}${s.repeated ? ` 반복해서 틀린 문항 ${s.repeated}문항.` : ''}</p>
      ${s.solved && s.rank === 5 ? '<p class="ox-sub">아직 풀어본 문항이 적어요. 더 학습하면 누적 정답률이 달라질 수 있어요.</p>' : ''}
      ${s.past && !s.wrong ? '<p class="ox-history-notice">이전 오답을 모두 다시 맞혔어요. 어려웠던 단원을 다시 복습할 수 있도록 목록에 남겨두었어요.</p>' : ''}
      ${s.past ? `<div class="ox-review-actions">${button(`이전 오답 ${s.past}문항 보기`, 'history-chapter', `data-id="${esc(s.c.id)}"`, 'ox-primary')}${button('이전 오답 다시 풀기', 'history-chapter-start', `data-id="${esc(s.c.id)}"`)}</div>` : button('이 단원 학습하기', 'chapter', `data-id="${esc(s.c.id)}"`, 'ox-wide')}
    </div>
  </details>`;
}

function weakness() {
  const list = weaknessStats();
  const weak = list.filter(s => s.past).sort(weaknessHistoryOrder);
  const noHistory = list.filter(s => !s.past && s.solved);
  const unlearned = list.filter(s => !s.solved);
  const counts = [
    { label: '취약 단원', count: weak.length, unit: '단원', tone: 'weak' },
    { label: '남은 오답', count: list.reduce((n, s) => n + s.wrong, 0), unit: '문항', tone: 'weak' },
    { label: '다시 맞힘', count: list.reduce((n, s) => n + s.regained, 0), unit: '문항', tone: 'good' }
  ];
  main.innerHTML = `<div class="ox-weak-heading">
      <h2>취약단원</h2>
      <details class="ox-weak-guide">
        <summary>계산 기준</summary>
        <div class="ox-weak-guide-body">
          <h3>누적 정답률은 어떻게 계산하나요?</h3>
          <p>정답 횟수 ÷ 전체 풀이 횟수 × 100이에요. 같은 문항을 다시 푼 횟수도 모두 포함해요.</p>
          <p>20회 풀어 8회 틀린 뒤 그 8문항을 모두 맞히면, 총 28회 중 20회 정답으로 71.4%가 돼요.</p>
          <p>이전 오답은 틀린 적 있는 문항 수예요. 같은 문항은 한 번만 세며, 다시 맞히거나 복습 완료해도 남아요. 남은 오답은 마지막 답변이 오답인 문항 수예요.</p>
          <p>현재 이용 가능한 공개 문항의 현재 버전으로 계산해요. 누적 정답률이 낮은 단원부터 보여드려요.</p>
          <p class="ox-sub">소수 첫째 자리까지 반올림해요. 오답 기록이 있으면 100%로 표시하지 않으며, 정렬에는 반올림 전 값을 사용해요.</p>
        </div>
      </details>
    </div>
    <p class="ox-sub">틀렸던 문항이 있는 단원이에요. 모두 다시 맞혀도 복습할 수 있도록 남겨두어요.</p>
    <div class="ox-weak-overview" aria-label="단원별 요약">
      ${counts.map(item => `<div><span>${item.label}</span><strong class="ox-weak-${item.tone}">${item.count}<small>${item.unit}</small></strong></div>`).join('')}
    </div>
    <p class="ox-sub">누적 정답률 낮은 순 · 단원을 누르면 이전 오답을 볼 수 있어요.</p>
    <section class="ox-weak-table" aria-label="취약 단원">
      <div class="ox-weak-columns" aria-hidden="true"><span>단원</span><span>누적 정답률</span><span>복습 상태</span><span></span></div>
      ${weak.length ? weak.map(weaknessRow).join('') : '<div class="ox-review-empty"><h3>아직 틀렸던 문항이 없어요.</h3><p class="ox-sub">한 번이라도 틀린 문항이 생기면 해당 단원을 여기에 보여드려요.</p></div>'}
    </section>
    ${noHistory.length ? `<details class="ox-weak-pending"><summary>오답 없는 단원 ${noHistory.length}개 보기</summary><div class="ox-weak-table">${noHistory.map(weaknessRow).join('')}</div></details>` : ''}
    ${unlearned.length ? `<details class="ox-weak-pending"><summary>미학습 ${unlearned.length}단원 보기</summary><div class="ox-weak-table">${unlearned.map(weaknessRow).join('')}</div></details>` : ''}`;
}

// Injected into the production mount closure by build-ox-learning.py.
const questionTextLoads = new Map();
let questionRenderVersion = 0;

function questionsForCurrentView() {
  if (typeof bookAccessBlocked !== 'undefined' && bookAccessBlocked) return [];
  if (route === 'quiz') {
    const start = Math.floor(session.index / 20) * 20;
    return session.ids.slice(start, start + 20).map(id => byId.get(id));
  }
  if (route === 'review') return reviewItemsForFilter().map(item => item.q);
  if (route === 'bookmarks') return bookmarkedQuestions();
  return [];
}

async function loadQuestionTexts(questions) {
  const missing = [...new Map(questions.filter(q => typeof q.prompt !== 'string').map(q => [q.id, q])).values()];
  const waiting = new Set(missing.map(q => questionTextLoads.get(q.id)).filter(Boolean));
  const fresh = missing.filter(q => !questionTextLoads.has(q.id));
  // At most 50 texts per request; large notebooks do not create a request storm.
  if (fresh.length) {
    const operation = (async () => {
      for (let offset = 0; offset < fresh.length; offset += 50) {
        const batch = fresh.slice(offset, offset + 50);
        const response = await request('questions', { questions: batch.map(q => ({id:q.id,version:q.version})) });
        const received = new Map((response.questions || []).map(q => [q.id,q]));
        // Validate the complete batch before changing any current question.
        for (const q of batch) {
          const value = received.get(q.id);
          if (!value || value.version !== q.version || typeof value.prompt !== 'string' || typeof value.context !== 'string') {
            throw Object.assign(new Error('question_changed'), {code:'question_changed'});
          }
        }
        for (const q of batch) {
          const value = received.get(q.id);
          q.prompt = value.prompt;
          q.context = value.context;
        }
      }
    })();
    const tracked = operation.finally(() => {
      for (const q of fresh) if (questionTextLoads.get(q.id) === tracked) questionTextLoads.delete(q.id);
    });
    for (const q of fresh) questionTextLoads.set(q.id, tracked);
    waiting.add(tracked);
  }
  await Promise.all(waiting);
}

function render() {
  const version = ++questionRenderVersion;
  const needed = questionsForCurrentView();
  if (!needed.some(q => typeof q.prompt !== 'string')) { renderLoadedView(); return; }
  renderNav();
  main.innerHTML = `<p class="ox-sub" role="status">문제를 불러오는 중입니다.</p>${button('돌아가기', 'nav', `data-ox-route="${origin}"`, 'ox-wide')}`;
  loadQuestionTexts(needed).then(() => {
    if (version === questionRenderVersion && root.isConnected) render();
  }).catch(error => {
    if (version !== questionRenderVersion || !root.isConnected) return;
    main.innerHTML = `${button('다시 시도', 'retry-questions', '', 'ox-primary')}${button('돌아가기', 'nav', `data-ox-route="${origin}"`)}`;
    showError(error);
  });
}

// Injected into the production learning closure. Access decisions come from the server.
let bookAccessBlocked = false;
const bookLabels = {'criminal-law':'형법','criminal-procedure-investigation-evidence':'수사·증거','criminal-procedure-trial':'공판'};
function bookTabs() {
  return `<div class="ox-filters ox-subject-filters" role="group" aria-label="학습 과목">${data.collections.map(c=>`<button type="button" class="mini-btn ox-filter" aria-pressed="${c.id===collection}" data-action="collection" data-id="${esc(c.id)}">${esc(bookLabels[c.id] || c.scope)}${c.accessible===false?' · 잠금':''}</button>`).join('')}</div>`;
}
function lockedBookView() {
  const title=bookLabels[collection] || '해당';
  main.innerHTML=`<h2>단원 학습</h2>${bookTabs()}<section class="ox-card"><h3>${esc(title)} 이용 권한 확인 필요</h3><p class="ox-sub">${esc(title)} 교재 구매 또는 이용권 지급이 필요한 영역입니다. 학원에 이용 권한을 확인해주세요.</p>${button('이용 권한 새로고침','refresh-books','','ox-wide')}</section>`;
}
function blockBookAccess(error) {
  if(!['ox_book_required','ox_not_registered','ox_disabled','unauthorized'].includes(error.code))return false;
  bookAccessBlocked=true;session=null;questionRenderVersion++;
  byId.clear();chapters.clear();progress.clear();notes.clear();statistics.clear();questionTextLoads.clear();
  data.questions.length=0;data.chapters.length=0;attempts.length=0;todayCount=0;
  renderBlockedBooks();
  return true;
}
function renderBlockedBooks() {
  nav.replaceChildren();nav.hidden=true;
  main.innerHTML=`<section class="ox-card" role="alert"><h2>이용 상태가 변경되었습니다</h2><p class="ox-sub">구매 권한과 이용 상태를 다시 확인해주세요. 기존 풀이 기록과 메모는 보존됩니다.</p>${button('이용 상태 새로고침','refresh-books','','ox-wide')}</section>`;
}

    function renderLoadedView(){if(bookAccessBlocked){renderBlockedBooks();return;} ({entry,home,chapters:chapterView,bookmarks:bookmarkView,'chapter-complete':chapterCompletionView,quiz,result,review,weak:weakness}[route]||home)(); renderNav(); if(globalThis.lucide)lucide.createIcons({attrs:{width:18,height:18}}); }
    root.addEventListener('toggle',async event=>{
      const details=event.target,id=details.dataset?.questionDetail;
      if(!id || !details.open || details.dataset.loading)return;
      const q=byId.get(id);if(q.explanation_html)return;
      details.dataset.loading='true';
      try {
        const saved=await request('detail',{questionId:id,version:q.version});
        Object.assign(q,saved.question);updateNote(saved.note);
        const wrapper=document.createElement('div');wrapper.innerHTML=reviewItemMarkup({q,...stats(id)});
        if(details.isConnected)details.innerHTML=wrapper.querySelector('details').innerHTML;
      }catch(error){showError(error);}finally{delete details.dataset.loading;}
    },true);
    root.addEventListener('click' ,async e=>{const b=e.target.closest('button[data-action]'); if(!b||b.disabled||pending)return; const action=b.dataset.action,id=b.dataset.id;
      try {
      if(action==='refresh-books'){onAccessRefresh?.();return;}
      if(bookAccessBlocked)return;
      if(action==='nav'){if(b.dataset.oxRoute==='review' && route!=='result')openReview();else route=b.dataset.oxRoute;}
      else if(action==='collection'){collection=id;allChapters=false;}
      else if(action==='chapter-size'){showChapterSizePicker();return;}
      else if(action==='law-part'){if(!['general','specific'].includes(b.dataset.part))return;criminalLawPart=b.dataset.part;allChapters=false;}
      else if(action==='expand-chapters')allChapters=!allChapters;
      else if(action==='expand-weak')allWeak=!allWeak;
      else if(action==='review-needed'){filter='복습 필요';openReview();}
      else if(action==='daily'){daily();return;}
      else if(action==='resume')route='quiz';
      else if(action==='session-result'){showSessionResult();return;}
      else if(action==='chapter'||action==='chapter-next'){startChapter(id);return;}
      else if(action==='chapter-wrong'){startChapter(id,'wrong');return;}
      else if(action==='chapter-continue'){continueChapterSet();return;}
      else if(action==='chapter-restart'){startChapter(id,'all');return;}
      else if(action==='one'){start([id],route==='bookmarks'?'북마크 문제':'오답 다시 풀기');return;}
      else if(action==='bookmarks-all'){start(bookmarkedQuestions().map(q=>q.id),'북마크 모아 풀기');return;}
      else if(action==='leave')route=origin;
      else if(action==='answer'){
        if(session.answers[session.index])return;
        const q=byId.get(session.ids[session.index]), answer=b.dataset.answer;
        session.submissions ||= {};
        session.submissions[session.index] ||= {id:crypto.randomUUID(),answer};
        const submission=session.submissions[session.index];
        const saved=await persist('submit',{questionId:q.id,version:q.version,answer:submission.answer,submissionId:submission.id});
        Object.assign(q,saved.question);progress.set(q.id,saved.progress);statistics.set(q.id,saved.statistics);updateNote(saved.note);
        for(const [id,counts] of Object.entries(saved.attemptCounts || {}))attemptCounts.set(id,counts);
        const a={id:q.id,answer:submission.answer,correct:submission.answer===q.correct_answer};attempts.push(a);todayCount++;session.answers[session.index]=a;
      }
      else if(action==='next'){if(!session.answers[session.index])return;session.index++; if(session.index===session.ids.length)route='result';}
      else if(action==='retry-session'){start(session.answers.filter(a=>!a.correct).map(a=>a.id),'방금 틀린 문제');return;}
      else if(action==='bookmark'){const saved=await persist('note',{questionId:id,version:byId.get(id).version,bookmark:!note(id).bookmark});updateNote(saved.note);}
      else if(action==='memo'){const saved=await persist('note',{questionId:id,version:byId.get(id).version,memo:root.querySelector('#ox-memo').value});updateNote(saved.note);root.querySelector('#ox-message').textContent='메모를 저장했어요.';return;}
      else if(action==='master'){const saved=await persist('note',{questionId:id,version:byId.get(id).version,mastered:!note(id).mastered});updateNote(saved.note);}
      else if(action==='history-chapter'){openReview('history',id);}
      else if(action==='history-chapter-start'){
        if(!chapters.has(id))return;
        start(reviews().filter(s=>s.q.chapter_id===id).map(s=>s.q.id),chapters.get(id).display_name+' · 이전 오답');return;
      }
      else if(action==='review-mode'){openReview(b.dataset.mode);}
      else if(action==='history-status'){if(['all','wrong','regained'].includes(b.dataset.status))reviewStatus=b.dataset.status;}
      else if(action==='history-repeat'){reviewRepeated=!reviewRepeated;}

      else if(action==='filter')filter=b.dataset.filter;
      else if(action==='review-all'){start(reviewItemsForFilter().map(s=>s.q.id),'오답 모아 풀기');return;}
      render();
      } catch(error){showError(error);}
    });

    render();
    return { openBookmarks() { if(bookAccessBlocked || pending || route==='quiz')return; route='bookmarks'; render(); } };
  })();
  
}
