const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const {PGlite}=require(process.env.OX_PGLITE_MODULE||'C:/Users/Public/Documents/ESTsoft/CreatorTemp/ox-db-tools/node_modules/@electric-sql/pglite');
const {createHandler,_private:{validate,invokeLearning}}=require('../api/criminal-law-ox');
const auth=require('../api/teacher-auth-utils');
const books=['criminal-law','criminal-procedure-investigation-evidence','criminal-procedure-trial'];
test('Bulk benefits: reviewed offline snapshot, pagination, purchase union, expiry, revocation, records and no automatic enrollment',async()=>{
 const db=new PGlite(),admin={type:'admin',id:'qa'},student=id=>({type:'student',id,deviceHash:crypto.createHash('sha256').update('phone').digest('hex')});
 const rpc=async(fn,action,actor,body={})=>(await db.query(`select ${fn}($1,$2::jsonb,$3::jsonb) result`,[action,JSON.stringify(actor),JSON.stringify(body)])).rows[0].result;
 const grant=(action,body={})=>rpc('ox_grant_admin','admin_grant_'+action,admin,body);
 const core=(action,body={})=>rpc('ox_service',action,admin,body);
 const learn=(action,id,body={})=>rpc('ox_device_gateway',action,student(id),body);
 const preview=(overrides={})=>grant('preview',{cohort:'18',collectionIds:books,expiresOn:null,reason:'재원생 학습 지원',...overrides});
 const register=async id=>db.query('select register_student_device($1,$2,$3)',[''+id,'fixture-password',student(id).deviceHash]);
 try{
  await db.exec("create role anon;create role authenticated;create role service_role bypassrls;create table students(id text primary key,name text default '학생',class_name text default '반',student_category text default 'offline',cohort smallint default 18,account_type text default 'student',is_active boolean default true);grant select on students to service_role;insert into students(id) select 's'||i from generate_series(0,34)i;insert into students(id,cohort) values('17001',null),('other',17);insert into students(id,student_category) values('online','online_managed'),('lecture','lecture');insert into students(id,is_active) values('inactive',false);insert into students(id,account_type) values('teacher','teacher');");
  await db.exec(fs.readFileSync('tests/fixtures/ox-app-devices.sql','utf8'));
  await db.exec(fs.readFileSync('supabase/add-student-devices.sql','utf8').replace('create extension if not exists "pgcrypto";',''));
  await db.exec('grant select on student_devices to service_role');
  await db.exec(fs.readFileSync('tests/fixtures/ox-lecture-identities.sql','utf8'));
  for(const name of ['20260917124608_criminal_law_ox.sql','20260917124623_criminal_law_ox_members.sql','20260920114238_ox_progressive_loading.sql','20260921113944_ox_book_access.sql','20260922044735_ox_member_cohort_filter.sql','20260922044751_ox_device_policy.sql','20260922044806_ox_verified_purchase_required.sql','20260922044821_ox_bulk_access_grants.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+name,'utf8'));
  await db.exec(fs.readFileSync('tests/fixtures/ox-exam-subjects.sql','utf8'));
  await db.exec(fs.readFileSync('supabase/migrations/20260922060528_ox_grant_recipient_selection.sql','utf8'));
  await db.exec(fs.readFileSync('supabase/migrations/20260922061015_ox_member_track_filter.sql','utf8'));
  await db.exec(fs.readFileSync('supabase/migrations/20261001082345_ox_managed_grants_and_fast_preview.sql','utf8'));
  await db.exec("insert into students(id,track) values('no-criminal','함정요원 순경 항해'),('no-written','함정요원'),('no-track',null),('unknown-track','확인 전 직렬');");
  const members=body=>core('admin_members',{registeredOnly:false,...body});
  const trackPage=await members({cohort:'18',track:'공채'});
  assert.equal(trackPage.total,36);assert.equal(trackPage.items.length,30);
  const trackNext=await members({cohort:'18',track:'경찰직 - 공채(순경)',page:1});
  assert.equal(trackNext.total,36);assert.equal(trackNext.items.length,6);
  assert.equal(new Set([...trackPage.items,...trackNext.items].map(s=>s.id)).size,36);
  assert.ok(trackPage.items.every(s=>s.track==='경찰직 - 공채(순경)'&&s.cohort==='18'));
  assert.equal((await members({cohort:'18',track:'공개채용',search:'s0'})).items[0].id,'s0');
  assert.equal((await members({cohort:'17',track:'확인 전 직렬'})).total,0);
  assert.equal((await members({cohort:'18',track:'확인 전 직렬'})).items[0].id,'unknown-track');
  assert.equal((await members({track:'unassigned'})).items[0].id,'no-track');
  assert.ok(trackPage.tracks.includes('확인 전 직렬'));
  assert.deepEqual((await members({cohort:'17'})).tracks,['경찰직 - 공채(순경)'],'Track choices follow the selected cohort');
  assert.equal(trackPage.tracks.filter(t=>t==='경찰직 - 공채(순경)').length,1);
  for(const track of [null,18,{},[],true,'x'.repeat(201)]){
    assert.throws(()=>validate({action:'admin_members',track}),/invalid_request/);
    await assert.rejects(members({track}),/invalid_request/);
  }
  await assert.rejects(rpc('ox_service','admin_members',{type:'student',id:'s0'},{track:'공채'}),/forbidden/);
  const eligible=async track=>(await db.query('select ox_grant_track_eligible($1) allowed',[track])).rows[0].allowed;
  for(const track of ['공채','공개채용','학과특채항해','수사특채','간부후보항해'])assert.equal(await eligible(track),true,track);
  for(const track of [null,'','기타','전체','확인 전 직렬','함정요원','함정요원순경기관','VTS'])assert.equal(await eligible(track),false,track);
  await db.exec("insert into exam_subject_settings(track,subject,is_active) values('수사특채','형사법',false),('확인된 별도 직렬','형사법',true),('함정요원','형사법',true)");
  assert.equal(await eligible('수사특채'),false,'Explicit disabled subject overrides defaults');
  assert.equal(await eligible('확인된 별도 직렬'),true,'Explicit settings support custom tracks');
  assert.equal(await eligible('함정요원'),false,'No written exam rule overrides stale subject settings');
  await db.exec("delete from exam_subject_settings");
  await core('admin_import',{collections:books.map((id,i)=>({id,sort_order:i})),chapters:books.map((id,i)=>({id:'c'+i,collection_id:id,sort_order:i})),questions:books.map((id,i)=>({id:'q'+i,chapter_id:'c'+i,prompt:'질문'+i,context:'',correct_answer:'O',explanation_html:'해설',source_question_number:String(i),reviewed:true,status:'published'}))});
  await core('admin_enabled',{enabled:true});for(const id of ['s0','s1','s2','online','lecture'])await register(id);
  await core('admin_member_set',{memberId:'s2',allowed:false});
  await db.exec('set role service_role');
  const targets=await grant('targets',{cohort:'18'});assert.equal(targets.items.length,35);
  assert.ok(targets.items.every(s=>s.cohort==='18' && Array.isArray(s.lecture_ids)));
  assert.equal((await db.query('select count(*)::int n from ox_grant_batches')).rows[0].n,0,'Browsing a roster creates no grant or draft');
  assert.deepEqual((await grant('targets',{cohort:'99'})).items,[]);
  await assert.rejects(rpc('ox_grant_admin','admin_grant_targets',student('s0'),{cohort:'18'}),/forbidden/);
  const first=(await preview()).batchId;
  const detail=await grant('detail',{batchId:first});assert.equal(detail.batch.target_count,35);assert.equal(detail.items.length,30);assert.equal((await grant('detail',{batchId:first,page:1})).items.length,5);
  assert.equal((await learn('status','s0')).enabled,false,'Preview grants no access');
  await assert.rejects(rpc('ox_grant_admin','admin_grant_issue',student('s0'),{batchId:first}),/forbidden/);
  await assert.rejects(rpc('ox_grant_admin','admin_grant_issue',{type:'admin',id:'other'},{batchId:first}),/grant_unavailable/);
  assert.equal((await grant('issue',{batchId:first})).count,35);await grant('issue',{batchId:first});
  assert.equal((await grant('list')).total,1,'Retry never duplicates a grant');
  for(const id of ['online','lecture'])assert.equal((await learn('status',id)).enabled,false,'Other categories remain purchase-gated');
  assert.equal((await learn('status','s2')).enabled,false,'Explicit whole-account suspension is preserved');
  await core('admin_member_set',{memberId:'s2',allowed:true,revision:1});assert.equal((await learn('status','s2')).enabled,true);
  const session=(await learn('device_start','s0')).sessionId;
  for(const summaryOnly of [false,true])assert.equal((await learn('bootstrap','s0',{sessionId:session,summaryOnly})).catalog.chapters.length,3);
  await learn('submit','s0',{sessionId:session,questionId:'q1',version:1,answer:'X',submissionId:crypto.randomUUID()});
  await learn('note','s0',{sessionId:session,questionId:'q1',version:1,memo:'이용권 학습 메모'});
  assert.equal((await learn('questions','s0',{sessionId:session,questions:[{id:'q1',version:1}]})).questions.length,1);
  assert.equal((await learn('detail','s0',{sessionId:session,questionId:'q1',version:1})).ok,true);
  assert.equal((await db.query("select count(*)::int n from ox_book_access")).rows[0].n,0,'Benefits never create fake purchases');
  await core('admin_book_set',{memberId:'s0',collectionIds:[books[0]],active:true,revision:0,purchaseDate:'2026-01-01',reason:'교재 구매'});
  await core('admin_book_set',{memberId:'s0',collectionIds:[books[0]],active:false,revision:1,reason:'구매 취소'});
  assert.equal((await learn('bootstrap','s0',{sessionId:session})).catalog.chapters.length,3,'Purchase cancellation does not revoke the separate benefit');
  await core('admin_book_set',{memberId:'s0',collectionIds:[books[0]],active:true,revision:2,purchaseDate:'2026-01-01',reason:'다시 구매'});
  const second=(await preview({collectionIds:[books[1]]})).batchId;await grant('issue',{batchId:second});
  await grant('revoke',{batchId:first,reason:'지원 종료'});await grant('revoke',{batchId:first,reason:'재시도'});
  assert.equal((await learn('bootstrap','s0',{sessionId:session})).catalog.chapters.length,2,'A different grant survives revocation');
  await grant('revoke',{batchId:second,reason:'종료'});
  assert.equal((await learn('bootstrap','s0',{sessionId:session})).catalog.chapters.length,1,'Purchased book survives all benefit revocations');
  for(const action of ['detail','submit','note','questions'])await assert.rejects(learn(action,'s0',{sessionId:session,questionId:'q1',version:1,answer:'O',submissionId:crypto.randomUUID(),questions:[{id:'q1',version:1}]}),/ox_book_required/);
  assert.equal((await learn('status','s1')).enabled,false);
  await assert.rejects(learn('device_start','s1'),/ox_book_required/);
  const stale=(await preview()).batchId;
  await db.exec('reset role');await db.exec("insert into students(id) values('new-student')");await db.exec('set role service_role');
  await assert.rejects(grant('issue',{batchId:stale}),/grant_target_changed/);
  const restored=(await preview({collectionIds:[books[1]]})).batchId;await grant('issue',{batchId:restored});
  const restoredData=await learn('bootstrap','s0',{sessionId:session});assert.equal(restoredData.progress.length,1);assert.equal(restoredData.notes[0].has_memo,true);
  const roster=await core('admin_members',{registeredOnly:true});assert.ok(roster.items.some(s=>s.grants?.length));
  await db.exec('reset role');await db.exec("insert into students(id) values('after-issue');update students set student_category='online_managed' where id='s1'");await register('after-issue');await db.exec('set role service_role');
  assert.equal((await learn('status','after-issue')).enabled,false,'No implicit grants to future enrollees');
  assert.equal((await learn('status','s1')).enabled,false,'Offline benefits stop on category change');
  await db.exec('reset role');await db.query("update ox_grant_batches set expires_on=(now() at time zone 'Asia/Seoul')::date-1 where id=$1",[restored]);await db.exec('set role service_role');
  assert.equal((await learn('bootstrap','s0',{sessionId:session})).catalog.chapters.length,1,'Expired grants do not remove purchases');
  const expired=(await preview()).batchId;await db.exec('reset role');await db.query("update ox_grant_batches set created_at=now()-interval '11 minutes' where id=$1",[expired]);await db.exec('set role service_role');
  await assert.rejects(grant('issue',{batchId:expired}),/grant_preview_expired/);
  await assert.rejects(preview({cohort:'99'}),/grant_empty_targets/);
  const legacyCohort=(await preview({cohort:'17'})).batchId;assert.equal((await grant('detail',{batchId:legacyCohort})).total,2,'Legacy ID cohort follows roster rule');
  for(const studentIds of [[],['s10','s10'],[null],[123],null])await assert.rejects(preview({studentIds}),/invalid_request/);
  for(const id of ['other','online','lecture','teacher','inactive','missing','no-criminal','no-written','no-track','unknown-track'])await assert.rejects(preview({studentIds:['s10',id]}),/grant_target_changed/);
  const chosen=(await preview({studentIds:['s10','s11'],collectionIds:[books[0]]})).batchId;
  assert.equal((await grant('detail',{batchId:chosen})).total,2);
  await db.exec('reset role');await db.exec("insert into students(id) values('later-18')");await db.exec('set role service_role');
  assert.equal((await grant('issue',{batchId:chosen})).count,2,'New classmates do not expand an explicit selection');
  assert.equal((await grant('issue',{batchId:chosen})).count,2,'Selected issue remains idempotent');
  const access=(await db.query("select ox_has_grant('s10',$1) chosen,ox_has_grant('s12',$1) excluded,ox_has_grant('later-18',$1) later",[books[0]])).rows[0];
  assert.deepEqual(access,{chosen:true,excluded:false,later:false});
  const changed=(await preview({studentIds:['s13','s14']})).batchId;
  await db.exec('reset role');await db.exec("update students set cohort=17 where id='s14'");await db.exec('set role service_role');
  await assert.rejects(grant('issue',{batchId:changed}),/grant_target_changed/);
  const deleted=(await preview({studentIds:['s15','s16']})).batchId;
  await db.exec('reset role');await db.exec("delete from students where id='s16'");await db.exec('set role service_role');
  await assert.rejects(grant('issue',{batchId:deleted}),/grant_target_changed/);
  const changedTrack=(await preview({studentIds:['s17']})).batchId;
  await db.exec('reset role');await db.exec("update students set track='VTS' where id='s17'");await db.exec('set role service_role');
  await assert.rejects(grant('issue',{batchId:changedTrack}),/grant_target_changed/);
  // Online managed grants are independent of offline cohorts and purchased books.
  await db.exec('reset role');
  await db.exec("insert into students(id,student_category,cohort,track) values('online-second','online_managed',null,'수사특채'),('online-no-exam','online_managed',18,'기타'),('online-inactive','online_managed',18,'공채'),('online-teacher','online_managed',18,'공채');update students set is_active=false where id='online-inactive';update students set account_type='teacher' where id='online-teacher';");
  await register('online-second');
  await db.exec('set role service_role');
  const managedTargets=await grant('targets',{cohort:'online_managed'});
  assert.deepEqual(managedTargets.items.map(s=>s.student_id).sort(),['online','online-second','s1']);
  assert.ok(!(await grant('targets',{cohort:''})).items.some(s=>s.student_id==='online'));
  for(const id of ['s0','lecture','online-no-exam','online-inactive','online-teacher'])await assert.rejects(preview({cohort:'online_managed',studentIds:[id]}),/grant_target_changed/);
  const managedPreview=(await preview({cohort:'online_managed',studentIds:['online','online-second'],collectionIds:[books[0]]})).batchId;
  assert.equal((await learn('status','online')).enabled,false,'Preview never grants access');
  assert.equal((await grant('detail',{batchId:managedPreview})).batch.cohort,'online_managed');
  assert.equal((await grant('issue',{batchId:managedPreview})).count,2);
  assert.equal((await grant('issue',{batchId:managedPreview})).count,2,'Retry does not duplicate recipients');
  assert.equal((await learn('status','online')).enabled,true);
  const managedSession=(await learn('device_start','online')).sessionId;
  assert.equal((await learn('bootstrap','online',{sessionId:managedSession})).catalog.chapters.length,1);
  assert.equal((await learn('status','s1')).enabled,false,'Other managed students do not inherit benefits');
  await db.exec('reset role');await db.exec("update students set is_active=false where id='online'");await db.exec('set role service_role');
  assert.equal((await db.query('select ox_has_grant($1,$2) allowed',['online',books[0]])).rows[0].allowed,false,'Inactive managed students lose access');
  await db.exec('reset role');await db.exec("update students set is_active=true,student_category='offline' where id='online'");await db.exec('set role service_role');
  assert.equal((await db.query('select ox_has_grant($1,$2) allowed',['online',books[0]])).rows[0].allowed,false,'Managed benefits do not transfer to offline enrollment');
  await db.exec('reset role');await db.exec("update students set student_category='online_managed' where id='online'");await db.exec('set role service_role');
  const managedChanged=(await preview({cohort:'online_managed',studentIds:['online-second']})).batchId;
  await db.exec('reset role');await db.exec("update students set student_category='lecture' where id='online-second'");await db.exec('set role service_role');
  await assert.rejects(grant('issue',{batchId:managedChanged}),/grant_target_changed/);
  await core('admin_book_set',{memberId:'online',collectionIds:[books[0]],active:true,revision:0,purchaseDate:'2026-01-01',reason:'managed purchase'});
  await grant('revoke',{batchId:managedPreview,reason:'managed grant revocation'});
  assert.equal((await learn('bootstrap','online',{sessionId:managedSession})).catalog.chapters.length,1,'Managed purchase survives benefit revocation');
  const changedSubjects=(await preview({studentIds:['s18']})).batchId;
  await db.exec('reset role');await db.exec("insert into exam_subject_settings(track,subject,is_active) values('경찰직 - 공채(순경)','형사법',false)");await db.exec('set role service_role');
  await assert.rejects(grant('issue',{batchId:changedSubjects}),/grant_target_changed/);
  await grant('revoke',{batchId:chosen,reason:'선택 지급 회수'});
  const privileges=(await db.query("select proname,prosecdef,has_function_privilege('anon',oid,'execute') anon,has_function_privilege('authenticated',oid,'execute') authenticated,has_function_privilege('service_role',oid,'execute') service from pg_proc where pronamespace='public'::regnamespace and proname in ('ox_grant_targets','ox_grant_admin','ox_has_grant')")).rows;
  assert.equal(privileges.length,3);
  for(const p of privileges){assert.equal(p.prosecdef,false);assert.equal(p.anon,false);assert.equal(p.authenticated,false);assert.equal(p.service,true);}
  for(const role of ['anon','authenticated']){await db.exec('reset role');await db.exec('set role '+role);await assert.rejects(grant('list'),/permission denied/);await assert.rejects(db.query('select * from ox_grant_batches'),/permission denied/);}
 }finally{await db.close();}
});
test('Grant API validates conditions and limits mutations to OX write permission',async()=>{
 const secret='grants-test';process.env.TEACHER_SESSION_SECRET=secret;const calls=[];
 const handler=createHandler({invoke:async(...args)=>{calls.push(args);return {ok:true};}});
 const request=async(body,permissions)=>{let code;await handler({method:'POST',headers:{host:'local',cookie:auth.COOKIE_NAME+'='+auth.createSessionToken(secret,{username:'qa',role:'teacher',permissions})},body},{setHeader(){},status(n){code=n;return this;},json(){}});return code;};
 const body={action:'admin_grant_preview',cohort:'18',collectionIds:books,expiresOn:null,reason:'지원'};
 assert.equal(await request(body,['criminal_ox.read']),403);assert.equal(await request(body,['criminal_ox.write']),200);
 for(const override of [{cohort:'lecture'},{collectionIds:[]},{collectionIds:[books[0],books[0]]},{expiresOn:'2026-02-31'},{reason:''}])assert.throws(()=>validate({...body,...override}),/invalid_request/);
 assert.equal(await request({action:'admin_grant_issue',batchId:crypto.randomUUID()},['criminal_ox.read']),403);
 assert.equal(await request({action:'admin_grant_revoke',batchId:crypto.randomUUID(),reason:'회수'},['criminal_ox.read']),403);
 assert.equal(await request({action:'admin_grant_list'},['criminal_ox.read']),200);
 assert.equal(await request({action:'admin_grant_targets',cohort:'18'},['criminal_ox.read']),200);
 assert.equal(await request({action:'admin_grant_targets',cohort:'online_managed'},['criminal_ox.read']),200);
 assert.equal(await request({...body,cohort:'online_managed',studentIds:['online']},['criminal_ox.write']),200);
 assert.equal(await request({...body,cohort:'online_managed'},['criminal_ox.read']),403);
 for(const cohort of [null,18,{},[],true,'online','online_managed18','100'])assert.throws(()=>validate({...body,cohort}),/invalid_request/);
 for(const studentIds of [[],['s','s'],[null],null])assert.throws(()=>validate({...body,studentIds}),/invalid_request/);
 assert.equal(await request({...body,studentIds:['s1']},['criminal_ox.write']),200);
 const paths=[];await invokeLearning('admin_grant_preview',{type:'admin',id:'qa'},body,async(...args)=>{paths.push(args);return {ok:true};});assert.equal(paths[0][1],'rpc/ox_grant_admin');
});


test('Grant preview keeps identical offline recipients while avoiding repeated roster scans',async()=>{
 const db=new PGlite();
 const read=file=>fs.readFileSync('supabase/migrations/'+file,'utf8').replace(/\r\n/g,'\n');
 const original=read('20260922060528_ox_grant_recipient_selection.sql');
 const migration=read('20261001082345_ox_managed_grants_and_fast_preview.sql');
 const functionSql=(sql,name)=>sql.match(new RegExp('create (?:or replace )?function public\\.'+name+'\\([^]*?\\$\\$;'))[0];
 const body={cohort:'18',studentIds:Array.from({length:55},(_,i)=>'bench'+i),collectionIds:[books[0]],expiresOn:null,reason:'performance fixture'};
 const preview=async()=>{
   await db.exec('begin');
   try {
     const start=performance.now();
     const result=await db.query("select ox_grant_admin('admin_grant_preview',$1::jsonb,$2::jsonb) result",[JSON.stringify({type:'admin',id:'qa'}),JSON.stringify(body)]);
     const ms=performance.now()-start;
     const snapshot=(await db.query('select student_id from ox_grant_recipients where batch_id=$1 order by student_id',[result.rows[0].result.batchId])).rows;
     return {ms,snapshot};
   } finally { await db.exec('rollback'); }
 };
 try {
   await db.exec("create role anon;create role authenticated;create role service_role bypassrls;create table students(id text primary key,name text default 'fixture',class_name text default 'class',student_category text default 'offline',cohort smallint default 18,account_type text default 'student',is_active boolean default true,track text);");
   await db.exec(fs.readFileSync('tests/fixtures/ox-exam-subjects.sql','utf8'));
   const initial=read('20260922044821_ox_bulk_access_grants.sql');
   await db.exec(initial.slice(0,initial.indexOf('create function public.ox_has_purchased_book')));
   await db.exec("alter table ox_grant_batches add column selection_mode text not null default 'all'");
   await db.exec(functionSql(original,'ox_normalize_grant_track')+functionSql(original,'ox_grant_track_eligible')+functionSql(original,'ox_grant_targets')+functionSql(original,'ox_grant_admin'));
   await db.exec("insert into students(id,track) select 'bench'||i,case when i<100 then '\uACF5\uCC44' else 'custom-track-'||(i%20) end from generate_series(0,319)i;insert into exam_subject_settings(track,subject,is_active) select case when t=0 then '\uACF5\uCC44' else 'custom-track-'||(t-1) end,case when s=0 then '\uD615\uC0AC\uBC95' else 'subject-'||s end,true from generate_series(0,20)t cross join generate_series(0,7)s;");
   // Read one actual old preview before replacing the functions.
   const before=await preview();
   await db.exec(functionSql(migration,'ox_grant_targets')+functionSql(migration,'ox_grant_admin'));
   const after=await preview();
   assert.equal(after.snapshot.length,55);
   assert.deepEqual(after.snapshot,before.snapshot,'Optimization must not change approved recipients');
   assert.ok(after.ms<before.ms/2,'Preview should avoid the previous per-student repeated settings scans');
   console.log('55-student preview with 320 students / 168 subject settings: '+Math.round(before.ms)+'ms -> '+Math.round(after.ms)+'ms');
   const parity=await db.query("select s.id from students s where ox_grant_track_eligible(s.track) is distinct from exists(select 1 from ox_grant_targets('18') t where t.student_id=s.id)");
   assert.equal(parity.rows.length,0,'Set-based eligibility matches existing track rules');
 } finally { await db.close(); }
});
