const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const {PGlite}=require(process.env.OX_PGLITE_MODULE || 'C:/Users/Public/Documents/ESTsoft/CreatorTemp/ox-db-tools/node_modules/@electric-sql/pglite');
const {createHandler,_private:{invokeLearning}}=require('../api/criminal-law-ox');
const auth=require('../api/teacher-auth-utils');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
test('Shared app devices: inherit registration, purchase isolation, replacement, quota, approvals, reset and leases',async()=>{
 const db=new PGlite(),admin={type:'admin',id:'qa'};
 const actor=(device,id='a',password=false)=>({type:'student',id,deviceHash:hash(device),...(password?{passwordHash:'fixture-password'}:{})});
 const sql=async(fn,action,who,body={})=>(await db.query(`select ${fn}($1,$2::jsonb,$3::jsonb) result`,[action,JSON.stringify(who),JSON.stringify(body)])).rows[0].result;
 const core=(action,body={})=>sql('ox_service',action,admin,body);
 const call=(action,device,body={},id='a')=>sql('ox_device_gateway',action,actor(device,id),body);
 const manage=(action,device,body={},id='a',password=false)=>sql('student_device_manage',action,actor(device,id,password),body);
 const register=async(device,id='a')=>(await db.query('select public.register_student_device($1,$2,$3,$4,$5) result',[id,'fixture-password',hash(device),'',device])).rows[0].result;
 const revoke=async(deviceId,device,id='a',who='student')=>(await db.query('select public.revoke_student_device($1,$2,$3,$4,$5) result',[id,hash(device),deviceId,who,'교체 해제'])).rows[0].result;
 try{
  await db.exec("create role anon;create role authenticated;create role service_role bypassrls;create table students(id text primary key,name text default '학생',class_name text default '반',student_category text default 'offline',cohort smallint default 18,account_type text default 'student',is_active boolean default true);grant select on students to service_role;insert into students(id) values('a'),('b'),('nonbuyer');");
  await db.exec(fs.readFileSync('tests/fixtures/ox-app-devices.sql','utf8'));
  await db.exec(fs.readFileSync('supabase/add-student-devices.sql','utf8').replace('create extension if not exists "pgcrypto";',''));
  await db.exec('grant select on student_devices to service_role');
  for(const m of ['20260917124608_criminal_law_ox.sql','20260917124623_criminal_law_ox_members.sql','20260920114238_ox_progressive_loading.sql','20260921113944_ox_book_access.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+m,'utf8'));
  await register('one');await register('two');await register('one','b');await register('one','nonbuyer');
  const original=(await db.query("select id from student_devices where student_id='a' order by id")).rows;
  await db.exec(fs.readFileSync('supabase/migrations/20260922044751_ox_device_policy.sql','utf8'));
  assert.deepEqual((await db.query("select id from student_devices where student_id='a' order by id")).rows,original,'Migration preserves all app device IDs');
  await core('admin_import',{collections:[{id:'criminal-law',sort_order:1},{id:'criminal-procedure-trial',sort_order:2}],chapters:[{id:'c',collection_id:'criminal-law',sort_order:1},{id:'trial',collection_id:'criminal-procedure-trial',sort_order:2}],questions:[{id:'q',chapter_id:'c',prompt:'질문',context:'',correct_answer:'O',explanation_html:'해설',source_question_number:'1',reviewed:true,status:'published'},{id:'trial-q',chapter_id:'trial',prompt:'미구매 문제',context:'',correct_answer:'X',explanation_html:'해설',source_question_number:'2',reviewed:true,status:'published'}]});
  for(const memberId of ['a','b'])await core('admin_book_set',{memberId,collectionIds:['criminal-law'],active:true,revision:0,purchaseDate:'2026-01-01',reason:'구매'});
  await core('admin_enabled',{enabled:true});await db.exec('set role service_role');
  let state=await call('device_state','one');assert.equal(state.registered,true);assert.equal(state.devices.length,2);assert.equal(state.activeSessionId,null);
  assert.equal((await register('three')).error,'device_limit_reached');
  let s1=(await call('device_start','one')).sessionId;
  assert.equal((await call('device_start','one')).sessionId,s1);
  await call('submit','one',{sessionId:s1,questionId:'q',version:1,answer:'X',submissionId:crypto.randomUUID()});
  await call('note','one',{sessionId:s1,questionId:'q',version:1,memo:'보존 메모',bookmark:true});
  // A legacy entitlement is not evidence of a book purchase, even on a valid device.
  await db.exec('reset role');
  await db.exec("insert into students(id) values('legacy');insert into ox_members(student_id,allowed,updated_by) values('legacy',true,'legacy');insert into ox_book_access(student_id,collection_id,source,updated_by) values('legacy','criminal-law','legacy','legacy'),('legacy','criminal-procedure-trial','legacy','legacy')");
  await register('one','legacy');
  const legacySession=(await call('device_start','one',{},'legacy')).sessionId;
  await call('submit','one',{sessionId:legacySession,questionId:'q',version:1,answer:'O',submissionId:crypto.randomUUID()},'legacy');
  await call('note','one',{sessionId:legacySession,questionId:'q',version:1,memo:'기존 기록 유지'},'legacy');
  await db.exec(fs.readFileSync('supabase/migrations/20260922044806_ox_verified_purchase_required.sql','utf8'));
  await db.exec('set role service_role');
  assert.equal((await call('status','one',{},'legacy')).enabled,false);
  for(const action of ['device_start','bootstrap','questions','detail','submit','note','device_heartbeat'])await assert.rejects(call(action,'one',{sessionId:legacySession},'legacy'),/ox_book_required/);
  await assert.rejects(core('admin_member_set',{memberId:'legacy',allowed:true,revision:1}),/book_selection_required/);
  await assert.rejects(db.exec("update ox_book_access set active=true where student_id='legacy'"),/ox_active_requires_verified_purchase/);
  await core('admin_book_set',{memberId:'legacy',collectionIds:['criminal-law'],active:true,revision:1,purchaseDate:'2026-01-01',reason:'구매 확인'});
  const restored=await call('bootstrap','one',{sessionId:legacySession},'legacy');assert.equal(restored.catalog.chapters.length,1);assert.equal(restored.progress.length,1);assert.equal(restored.notes[0].has_memo,true);
  for(const action of ['detail','submit','note'])await assert.rejects(call(action,'one',{sessionId:s1,questionId:'trial-q',version:1,answer:'O',submissionId:crypto.randomUUID()}),/question_unavailable|ox_book_required/);
  await assert.rejects(call('questions','one',{sessionId:s1,questions:[{id:'trial-q',version:1}]}),/question_unavailable|ox_book_required/);
  for(const summaryOnly of [false,true]){
   const data=await call('bootstrap','one',{sessionId:s1,summaryOnly});assert.equal(data.catalog.chapters.length,1);assert.equal(JSON.stringify(data).includes('미구매 문제'),false);
  }
  await assert.rejects(call('device_start','two'),/device_in_use/);
  const s2=(await call('device_start','two',{takeover:true,expectedSessionId:s1})).sessionId;
  for(const action of ['bootstrap','questions','detail','submit','note','device_heartbeat'])await assert.rejects(call(action,'one',{sessionId:s1}),/device_session_changed/);
  await assert.rejects(manage('device_state','three'),/unauthorized/);
  await assert.rejects(call('device_start','three'),/unauthorized/);
  state=await manage('device_state','three',{},'a',true);
  await manage('device_replace','three',{targetDeviceId:state.devices.find(d=>d.label==='one').id,reason:'휴대폰 교체',deviceLabel:'three'},'a',true);
  assert.equal((await register('three')).status,'already_registered');
  await assert.rejects(call('bootstrap','one',{sessionId:s1}),/unauthorized/);
  state=await manage('device_state','four',{},'a',true);assert.equal(state.canReplace,false);assert.equal(state.devices.length,2);
  const target=state.devices.find(d=>d.label==='two').id;
  await assert.rejects(manage('device_replace','four',{targetDeviceId:target,reason:'추가'},'a',true),/device_replace_limit/);
  assert.equal((await revoke(target,'three')).error,'device_replace_limit','Legacy revoke cannot bypass cooldown');
  const reset=await db.query("select reset_student_devices('a','fixture-password','student','우회') result");
  assert.equal(reset.rows[0].result.error,'device_replacement_required');
  await manage('device_request','four',{targetDeviceId:target,reason:'고장',deviceLabel:'four'},'a',true);
  await manage('device_request','four',{targetDeviceId:target,reason:'중복',deviceLabel:'four'},'a',true);
  let requests=await sql('student_device_manage','admin_device_requests',admin);assert.equal(requests.total,1);
  const requestId=requests.items[0].id;
  await assert.rejects(manage('admin_device_requests','three'),/forbidden/);
  await sql('student_device_manage','admin_device_decide',admin,{requestId,approve:true,reason:'고장 확인'});
  await assert.rejects(sql('student_device_manage','admin_device_decide',admin,{requestId,approve:true,reason:'중복'}),/device_request_changed/);
  assert.equal((await register('four')).status,'already_registered');
  await assert.rejects(call('bootstrap','two',{sessionId:s2}),/unauthorized/);
  const s4=(await call('device_start','four')).sessionId;
  const records=await call('bootstrap','four',{sessionId:s4});assert.equal(records.progress.length,1);assert.equal(records.notes[0].has_memo,true);
  const validation=(await db.query('select validate_student_device($1,$2) result',['a',hash('two')])).rows[0].result;assert.equal(validation.error,'device_not_active');
  assert.equal((await call('device_state','one',{},'nonbuyer')).learningError,'ox_not_registered');
  assert.equal((await manage('device_state','one',{},'nonbuyer')).registered,true);
  for(const action of ['device_start','bootstrap','questions','detail','submit','note','device_heartbeat'])await assert.rejects(call(action,'one',{},'nonbuyer'),/ox_not_registered/);
  await core('admin_book_set',{memberId:'nonbuyer',collectionIds:['criminal-law'],active:true,revision:0,purchaseDate:'2026-01-01',reason:'구매'});
  const ns=(await call('device_start','one',{},'nonbuyer')).sessionId;
  assert.equal((await call('bootstrap','one',{sessionId:ns},'nonbuyer')).catalog.chapters.length,1);
  await core('admin_book_set',{memberId:'nonbuyer',collectionIds:['criminal-law'],active:false,revision:1,reason:'반품'});
  assert.equal((await manage('device_state','one',{},'nonbuyer')).registered,true);
  await assert.rejects(call('bootstrap','one',{sessionId:ns},'nonbuyer'),/ox_book_required/);
  await db.exec('reset role');await db.exec("update student_device_changes set changed_at=now()-interval '31 days'");await db.exec('set role service_role');
  state=await manage('device_state','three');assert.equal(state.canReplace,true);
  assert.equal((await revoke(state.devices.find(d=>d.label==='four').id,'three')).revoked,true);
  assert.equal((await register('five')).status,'registered');
  await assert.rejects(call('device_heartbeat','four',{sessionId:s4}),/unauthorized/);
  state=await manage('device_state','six',{},'a',true);
  await manage('device_request','six',{targetDeviceId:state.devices.find(d=>d.label==='five').id,reason:'신청'},'a',true);
  requests=await sql('student_device_manage','admin_device_requests',admin);
  await db.exec('reset role');await db.exec("update students set password_hash='changed' where id='a'");await db.exec('set role service_role');
  await assert.rejects(sql('student_device_manage','admin_device_decide',admin,{requestId:requests.items[0].id,approve:true,reason:'오래된 인증'}),/device_unavailable/);
  await db.query("select reset_student_devices('a','','teacher','비밀번호 초기화')");
  await assert.rejects(call('device_start','three'),/unauthorized/);
  assert.equal((await sql('student_device_manage','admin_device_requests',admin)).total,0);
  const info=await sql('student_device_manage','admin_device_list',admin,{memberId:'a'});assert.equal(info.canReplace,false);assert.equal(JSON.stringify(info).includes(hash('three')),false);
  await register('two','b');
  const simultaneous=await Promise.allSettled(['one','two'].map(d=>call('device_start',d,{},'b')));
  assert.equal(simultaneous.filter(r=>r.status==='fulfilled').length,1);
  assert.equal(simultaneous.filter(r=>r.status==='rejected').length,1);
  await assert.rejects(call('bootstrap','one',{sessionId:s4},'b'),/device_session_changed/);
  for(const role of ['anon','authenticated']){
   await db.exec('reset role');await db.exec('set role '+role);
   await assert.rejects(manage('device_state','one',{},'b'),/permission denied/);
   await assert.rejects(call('device_start','one',{},'b'),/permission denied/);
   await assert.rejects(db.query('select * from student_device_requests'),/permission denied/);
  }
  await db.exec('reset role');assert.equal((await db.query("select to_regclass('public.ox_devices') as name")).rows[0].name,null,'No duplicate device registry');
  assert.equal((await db.query("select count(*)::int n from pg_class where relname in ('ox_device_sessions','student_device_changes','student_device_requests') and relrowsecurity")).rows[0].n,3);
  assert.equal((await db.query("select bool_and(not prosecdef) as safe from pg_proc where oid in ('public.ox_device_gateway(text,jsonb,jsonb)'::regprocedure,'public.student_device_manage(text,jsonb,jsonb)'::regprocedure,'public.revoke_student_device(text,text,uuid,text,text)'::regprocedure,'public.reset_student_devices(text,text,text,text,text,text)'::regprocedure)")).rows[0].safe,true);
 }finally{await db.close();}
});

test('API binds gateway to server-derived device identity and protects exception approvals',async()=>{
  const calls=[];
  await invokeLearning('bootstrap',{type:'student',id:'a',deviceHash:hash('one')},{sessionId:'session'},async(...args)=>{calls.push(args);return {ok:true};});
  assert.equal(calls[0][1],'rpc/ox_device_gateway');
  const secret='device-policy-tests';process.env.TEACHER_SESSION_SECRET=secret;
  const seen=[];const handler=createHandler({authenticate:async()=>({id:'a'}),sessionSecret:()=>secret,invoke:async(...args)=>{seen.push(args);return {ok:true};}});
  const req=async(body,permissions)=>{let code,result;const cookie=permissions?auth.COOKIE_NAME+'='+auth.createSessionToken(secret,{username:'teacher',role:'teacher',permissions}):'';await handler({method:'POST',headers:{host:'localhost',cookie},body},{setHeader(){},status(c){code=c;return this;},json(v){result=v;}});return {code,result};};
  await req({action:'device_state',studentId:'a',deviceToken:'one',actor:{type:'admin'},deviceHash:'fake'});
  assert.equal(seen[0][1].deviceHash,hash('one'));assert.equal(seen[0][1].type,'student');
  const approval={action:'admin_device_decide',requestId:crypto.randomUUID(),approve:true,reason:'확인'};
  assert.equal((await req(approval,['criminal_ox.write'])).code,403);
  assert.equal((await req(approval,['students.reset'])).code,200);
  assert.equal((await req({action:'admin_device_requests'},['criminal_ox.read'])).code,403);
  assert.equal((await req({action:'admin_device_requests'},['students.read'])).code,200);
});

test('Shared management API constructs identity and never accepts book grants or forged administrators',async()=>{
 const secret='shared-device-tests',calls=[];process.env.TEACHER_SESSION_SECRET=secret;
 const handler=require('../api/student-devices').createHandler({manage:async args=>{calls.push(args);return {ok:true,registered:false};}});
 const invoke=async(body,permissions)=>{
  const res={headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(v){this.body=v;}};
  const cookie=permissions?auth.COOKIE_NAME+'='+auth.createSessionToken(secret,{username:'teacher',role:'teacher',permissions}):'';
  await handler({method:'POST',headers:{host:'localhost',cookie},body},res);return res;
 };
 const candidate={action:'device_state',studentId:'a',deviceToken:'unregistered',passwordHash:'password',actor:{type:'admin',id:'other'},collectionIds:['criminal-law'],active:true};
 assert.equal((await invoke(candidate)).code,200);
 assert.deepEqual(calls[0].p_actor,{type:'student',id:'a',deviceHash:hash('unregistered'),passwordHash:'password'});
 assert.equal(calls[0].p_body.collectionIds,undefined);assert.equal(calls[0].p_body.active,undefined);
 assert.equal((await invoke({...candidate,action:'admin_book_set'})).code,400);
 assert.equal((await invoke({...candidate,action:'admin_device_requests'})).code,401);
 assert.equal((await invoke({action:'admin_device_requests'},['criminal_ox.read'])).code,403);
 assert.equal((await invoke({action:'admin_device_requests'},['students.read'])).code,200);
 const approval={action:'admin_device_decide',requestId:crypto.randomUUID(),approve:true,reason:'고장 확인'};
 assert.equal((await invoke(approval,['students.read'])).code,403);
 assert.equal((await invoke(approval,['students.reset'])).code,200);
 assert.equal((await invoke({...approval,approve:'true'},['students.reset'])).code,400);
});
