const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('fs');
const crypto=require('crypto');
const {PGlite}=require(process.env.OX_PGLITE_MODULE || 'C:/Users/Public/Documents/ESTsoft/CreatorTemp/ox-db-tools/node_modules/@electric-sql/pglite');
const {createHandler}=require('../api/criminal-law-ox');
const auth=require('../api/teacher-auth-utils');
test('OX SQL: publication, grading, deduplication, student isolation, revisions, notes and RLS',async()=>{
  const db=new PGlite();
  try {
    await db.exec("create role anon;create role authenticated;create role service_role bypassrls;create table students(id text primary key,is_active boolean default true);insert into students values('a',true),('b',true),('inactive',false);grant select on students to service_role;");
    await db.exec(fs.readFileSync('supabase/migrations/20260917124608_criminal_law_ox.sql','utf8'));
    await db.exec("alter table students add column name text default '수강생';alter table students add column class_name text default '테스트반';alter table students add column student_category text default 'offline';alter table students add column account_type text default 'student';");
    await db.exec('update ox_config set enabled=true');
    await db.exec(fs.readFileSync('supabase/migrations/20260917124623_criminal_law_ox_members.sql','utf8'));
    assert.equal((await db.query('select enabled from ox_config')).rows[0].enabled,false);
    const admin={type:'admin',id:'teacher'},a={type:'student',id:'a'},b={type:'student',id:'b'};
    const call=async(action,actor,body={})=>(await db.query('select ox_service($1,$2::jsonb,$3::jsonb) result',[action,JSON.stringify(actor),JSON.stringify(body)])).rows[0].result;
    const q={id:'q1',chapter_id:'c1',prompt:'지문',context:'',correct_answer:'O',explanation_html:'<u>해설</u>',explanation:'해설',source_question_number:'1',original_prompt:'원래 지문'};
    await call('admin_import',admin,{collections:[{id:'book',sort_order:1}],chapters:[{id:'c1',collection_id:'book',sort_order:1}],questions:[{...q,reviewed:true,status:'published'},{...q,id:'draft',status:'draft'}]});
    await assert.rejects(call('admin_catalog',a),/forbidden/);
    await assert.rejects(call('admin_catalog',{id:'a'}),/unauthorized/);
    await assert.rejects(call('bootstrap',a),/ox_disabled/);
    assert.equal((await call('status',a)).enabled,false);
    await call('admin_enabled',admin,{enabled:true});
    assert.equal((await call('status',a)).enabled,false);
    for(const action of ['bootstrap','detail','submit','note']) await assert.rejects(call(action,a),/ox_not_registered/);
    await assert.rejects(call('admin_member_set',a,{memberId:'a',allowed:true}),/forbidden/);
    for(const id of ['a','b']) await call('admin_member_set',admin,{memberId:id,allowed:true});
    assert.equal((await call('status',a)).enabled,true);
    await assert.rejects(call('bootstrap',{type:'student',id:'inactive'}),/unauthorized/);
    let initial=await call('bootstrap',a);
    assert.equal(initial.catalog.questions.length,1);assert.equal(initial.catalog.chapters[0].question_count,1);
    assert.equal(initial.catalog.questions[0].correct_answer,undefined);assert.equal(initial.catalog.questions[0].explanation_html,undefined);
    await assert.rejects(call('detail',a,{questionId:'q1',version:1}),/answer_required/);
    await assert.rejects(call('submit',a,{questionId:'q1',answer:'X',submissionId:crypto.randomUUID()}),/question_changed/);
    const submit={questionId:'q1',version:1,answer:'X',submissionId:crypto.randomUUID()};
    const first=await call('submit',a,submit);
    assert.equal(first.progress.correct,false);assert.equal(first.progress.wrong_count,1);assert.equal(first.question.correct_answer,'O');assert.deepEqual(first.statistics,{answered:1,wrong:1});
    const retry=await call('submit',a,submit);assert.equal(retry.progress.wrong_count,1);assert.deepEqual(retry.statistics,first.statistics);
    await assert.rejects(call('submit',a,{...submit,answer:'O'}),/submission_conflict/);
    await call('submit',a,{...submit,answer:'O',submissionId:crypto.randomUUID()});
    let after=await call('bootstrap',a);assert.equal(after.todayCount,2);assert.equal(after.progress[0].correct,true);assert.equal(after.progress[0].wrong_count,1);
    assert.deepEqual(after.statistics.q1,{answered:1,wrong:1});
    assert.equal((await call('bootstrap',b)).progress.length,0);
    const second=await call('submit',b,{...submit,answer:'O',submissionId:crypto.randomUUID()});assert.deepEqual(second.statistics,{answered:2,wrong:1});
    await call('note',a,{questionId:'q1',version:1,memo:'메모'});await call('note',a,{questionId:'q1',version:1,bookmark:true,mastered:true});
    after=await call('bootstrap',a);assert.equal(after.notes[0].has_memo,true);assert.equal(after.notes[0].memo,undefined);assert.equal(after.notes[0].bookmark,true);assert.equal(after.notes[0].mastered_version,1);assert.equal((await call('bootstrap',b)).notes.length,0);
    assert.equal(after.catalog.questions[0].explanation_html,undefined);
    const detail=await call('detail',a,{questionId:'q1',version:1});assert.equal(detail.note.memo,'메모');assert.equal(detail.question.explanation_html,'<u>해설</u>');
    // Removing an item from the notebook keeps its learning history and memo.
    // A subsequent wrong answer returns it to the notebook.
    const readded=await call('submit',a,{...submit,submissionId:crypto.randomUUID()});
    assert.equal(readded.note.mastered_version,null);assert.equal(readded.note.memo,'메모');assert.equal(readded.note.bookmark,true);assert.equal(readded.progress.wrong_count,2);
    const edit=await call('admin_save',admin,{question:{...q,prompt:'수정 지문',original_prompt:'변조 시도'},revision:1,status:'published',reviewed:true});
    assert.equal(edit.item.content_version,2);assert.equal(edit.item.entry.original_prompt,'원래 지문');
    await assert.rejects(call('admin_save',admin,{question:q,revision:1,status:'published',reviewed:true}),/revision_conflict/);
    await assert.rejects(call('admin_save',admin,{question:q,status:'published',reviewed:true}),/revision_conflict/);
    await assert.rejects(call('submit',a,{...submit,submissionId:crypto.randomUUID()}),/question_changed/);
    after=await call('bootstrap',a);assert.equal(after.progress.length,0);assert.equal(after.catalog.questions[0].correct_answer,undefined);assert.equal(after.notes[0].has_memo,true);
    assert.equal((await call('admin_history',admin,{id:'q1'})).history.length,1);
    const explanation=await call('admin_save',admin,{question:{...q,prompt:'수정 지문',explanation_html:'해설 보완'},revision:2,status:'published',reviewed:true});assert.equal(explanation.item.content_version,2);
    await assert.rejects(call('admin_save',admin,{question:{...q,id:'q-new'},revision:0,status:'published',reviewed:false}),/invalid_question/);
    const added=await call('admin_save',admin,{question:{...q,id:'q-new'},revision:0,status:'draft',reviewed:false});assert.equal(added.item.revision,1);
    await call('admin_save',admin,{question:added.item.entry,revision:1,status:'archived',reviewed:false});assert.equal((await call('admin_catalog',admin)).counts.archived,1);
    await call('admin_member_set',admin,{memberId:'a',allowed:false});
    assert.equal((await call('status',a)).enabled,false);
    for(const action of ['bootstrap','detail','submit','note']) await assert.rejects(call(action,a,{questionId:'q1',version:2}),/ox_not_registered/);
    assert.equal((await call('status',b)).enabled,true);
    await call('admin_member_set',admin,{memberId:'a',allowed:true});
    assert.equal((await call('bootstrap',a)).notes[0].has_memo,true);
    assert.equal((await db.query("select count(*)::int as n from ox_attempts where student_id='a'")).rows[0].n,3);
    await call('admin_enabled',admin,{enabled:false});
    assert.equal((await call('status',a)).enabled,false);
    await assert.rejects(call('submit',a,submit),/ox_disabled/);
    for(const id of ['inactive','missing']) await assert.rejects(call('admin_member_set',admin,{memberId:id,allowed:true}),/student_unavailable/);
    assert.equal((await call('admin_members',admin)).total,2);
    assert.equal((await call('admin_members',admin,{search:'b'})).items[0].id,'b');
    assert.equal((await call('admin_members',admin,{page:1})).items.length,0);
    await db.exec('set role anon');
    await assert.rejects(db.query('select * from ox_members'),/permission denied/);
    await assert.rejects(db.query("insert into ox_members(student_id,updated_by) values('inactive','forged')"),/permission denied/);
    await assert.rejects(db.query('select * from ox_questions'),/permission denied/);
    await assert.rejects(call('admin_catalog',admin),/permission denied/);
    await db.exec('reset role;set role authenticated');
    await assert.rejects(db.query('select * from ox_members'),/permission denied/);
    await assert.rejects(call('admin_member_set',admin,{memberId:'a',allowed:true}),/permission denied/);
    await db.exec('reset role;set role service_role');assert.equal((await call('admin_catalog',admin)).counts.total,3);
    assert.equal((await call('admin_members',admin)).total,2);
    await call('admin_member_set',admin,{memberId:'a',allowed:false});
    assert.equal((await call('admin_members',admin)).total,1);
    assert.equal((await call('admin_members',admin,{registeredOnly:false})).total,2);
  } finally { await db.close(); }
});

test('OX member roster paginates, exposes only display fields and denies inactive/teacher accounts',async()=>{
  const db=new PGlite();
  try {
    await db.exec("create role anon;create role authenticated;create role service_role bypassrls;create table students(id text primary key,name text,class_name text,student_category text,account_type text default 'student',is_active boolean default true,password_hash text default 'private');grant select on students to service_role;");
    for(const file of ['20260917124608_criminal_law_ox.sql','20260917124623_criminal_law_ox_members.sql']) await db.exec(fs.readFileSync('supabase/migrations/'+file,'utf8'));
    await db.exec("insert into students(id,name,class_name,student_category) select 's'||n,'Student '||lpad(n::text,2,'0'),'Class','lecture' from generate_series(1,35)n;insert into students(id,name,account_type) values('teacher','Teacher','teacher');");
    const admin={type:'admin',id:'admin'};
    const call=async(action,actor=admin,body={})=>(await db.query('select ox_service($1,$2::jsonb,$3::jsonb) result',[action,JSON.stringify(actor),JSON.stringify(body)])).rows[0].result;
    assert.equal((await call('admin_members')).total,0);
    const first=await call('admin_members',admin,{registeredOnly:false}),second=await call('admin_members',admin,{registeredOnly:false,page:1});
    assert.equal(first.total,35);assert.equal(first.items.length,30);assert.equal(second.items.length,5);
    assert.equal(new Set([...first.items,...second.items].map(s=>s.id)).size,35);
    assert.ok(first.items.every(s=>s.password_hash===undefined));
    await assert.rejects(call('admin_member_set',admin,{memberId:'teacher',allowed:true}),/student_unavailable/);
    await call('admin_member_set',admin,{memberId:'s1',allowed:true});
    await call('admin_enabled',admin,{enabled:true});
    await db.exec("update students set is_active=false where id='s1'");
    assert.equal((await call('admin_members')).items[0].is_active,false);
    await assert.rejects(call('bootstrap',{type:'student',id:'s1'}),/unauthorized/);
    await call('admin_member_set',admin,{memberId:'s1',allowed:false});
    await assert.rejects(call('admin_member_set',admin,{memberId:'s1',allowed:true}),/student_unavailable/);
    await assert.rejects(call('status',{type:'student',id:'teacher'}),/unauthorized/);
    assert.equal((await db.query("select relrowsecurity from pg_class where oid='public.ox_members'::regclass")).rows[0].relrowsecurity,true);
    assert.equal((await db.query("select prosecdef from pg_proc where oid='public.ox_service(text,jsonb,jsonb)'::regprocedure")).rows[0].prosecdef,false);
  } finally {await db.close();}
});
test('OX API rejects forged actors and unsupported imports; enforces teacher permissions and validates input',async()=>{
  process.env.TEACHER_SESSION_SECRET='ox-unit-test-only';
  const calls=[];
  const handler=createHandler({authenticate:async body=>body.deviceToken==='valid'?{id:'actual-student'}:null,invoke:async(...args)=>{calls.push(args);return {ok:true};}});
  async function request(body,cookie,origin) {let result,status;const req={method:'POST',headers:{host:'localhost',cookie:cookie || '',...(origin?{origin}:{})},body};const res={setHeader(){},status(v){status=v;return this;},json(v){result=v;}};await handler(req,res);return {status,result};}
  assert.equal((await request({action:'bootstrap',actor:{type:'admin'}})).status,401);
  const cookie=permissions=>`${auth.COOKIE_NAME}=${auth.createSessionToken(process.env.TEACHER_SESSION_SECRET,{username:'teacher',role:'teacher',permissions})}`;
  assert.equal((await request({action:'admin_catalog',deviceToken:'valid'})).status,401);
  assert.equal((await request({action:'admin_enabled',enabled:true},cookie(['criminal_ox.read']))).status,403);
  assert.equal((await request({action:'admin_catalog'},cookie(['criminal_ox.read']))).status,200);
  assert.equal((await request({action:'admin_import'},cookie(['*']))).status,400);
  assert.equal((await request({action:'bootstrap',deviceToken:'valid',actor:{type:'admin',id:'forged'},studentId:'forged'})).status,200);
  const latest=calls.at(-1);assert.deepEqual(latest[1],{type:'student',id:'actual-student'});assert.equal(latest[2].actor,undefined);assert.equal(latest[2].deviceToken,undefined);
  assert.equal((await request({action:'bootstrap',deviceToken:'valid'},null,'https://attacker.test')).status,403);
  assert.equal((await request({action:'note',questionId:'q',version:1,memo:null,deviceToken:'valid'})).status,400);
  assert.equal((await request({action:'submit',questionId:'q',version:1,answer:'?',submissionId:crypto.randomUUID(),deviceToken:'valid'})).status,400);
  assert.equal((await request({action:'admin_members'},cookie(['criminal_ox.read']))).status,200);
  assert.equal((await request({action:'admin_member_set',memberId:'a',allowed:true},cookie(['criminal_ox.read']))).status,403);
  assert.equal((await request({action:'admin_member_set',memberId:'a',allowed:false},cookie(['criminal_ox.read']))).status,403);
  assert.equal((await request({action:'admin_members'},cookie([]))).status,403);
  assert.equal((await request({action:'admin_member_set',memberId:'a',allowed:true},cookie(['criminal_ox.write']))).status,200);
  assert.equal(calls.at(-1)[2].memberId,'a');
  for(const body of [{memberId:'',allowed:true},{memberId:'a',allowed:'true'},{memberId:'a'}]) assert.equal((await request({action:'admin_member_set',...body},cookie(['*']))).status,400);
  assert.equal((await request({action:'admin_members',registeredOnly:'false'},cookie(['*']))).status,400);
  assert.equal((await request({action:'admin_members',page:-1},cookie(['*']))).status,400);
});
test('production learning bundle has no sample records or embedded answer bank',()=>{
  const source=fs.readFileSync('criminal-law-ox.js','utf8');
  assert.ok(!/exampleQuestionStats|seedChapterCompletionPreview|criminal-law-003|standaloneDerivedIds/.test(source));
  assert.ok(source.includes("persist('submit'"));assert.ok(source.includes("persist('note'"));
});
