const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const {PGlite}=require(process.env.OX_PGLITE_MODULE||'C:/Users/Public/Documents/ESTsoft/CreatorTemp/ox-db-tools/node_modules/@electric-sql/pglite');
const {createHandler,_private:{validate,invokeLearning}}=require('../api/criminal-law-ox');
const auth=require('../api/teacher-auth-utils');
const books=['criminal-law','criminal-procedure-investigation-evidence','criminal-procedure-trial'];
test('Bulk benefits: reviewed offline snapshot, pagination, purchase union, expiry, revocation, records and no automatic enrollment',async()=>{
 const db=new PGlite(),admin={type:'admin',id:'qa'},student=id=>({type:'student',id,deviceHash:crypto.createHash('sha256').update('phone').digest('hex')});
 const rpc=async(fn,action,actor,body={})=>(await db.query(`select ${fn}($1,$2::jsonb,$3::jsonb) result`,[action,JSON.stringify(actor),JSON.stringify(body)])).rows[0].result;
 const grant=(action,body={})=>rpc('ox_grant_admin','admin_grant_'+action,admin,body);
 const core=(action,body={})=>rpc('ox_service',action,admin,body);
 const learn=(action,id,body={})=>rpc('ox_device_gateway',action,student(id),body);
 const preview=(overrides={})=>grant('preview',{cohort:'18',collectionIds:books,expiresOn:null,reason:'재원생 학습 지원',...overrides});
 const register=async id=>db.query('select register_student_device($1,$2,$3)',[''+id,'fixture-password',student(id).deviceHash]);
 try{
  await db.exec("create role anon;create role authenticated;create role service_role bypassrls;create table students(id text primary key,name text default '학생',class_name text default '반',student_category text default 'offline',cohort smallint default 18,account_type text default 'student',is_active boolean default true);grant select on students to service_role;insert into students(id) select 's'||i from generate_series(0,34)i;insert into students(id,cohort) values('17001',null),('other',17);insert into students(id,student_category) values('online','online_managed'),('lecture','lecture');insert into students(id,is_active) values('inactive',false);insert into students(id,account_type) values('teacher','teacher');");
  await db.exec(fs.readFileSync('tests/fixtures/ox-app-devices.sql','utf8'));
  await db.exec(fs.readFileSync('supabase/add-student-devices.sql','utf8').replace('create extension if not exists "pgcrypto";',''));
  await db.exec('grant select on student_devices to service_role');
  await db.exec(fs.readFileSync('tests/fixtures/ox-lecture-identities.sql','utf8'));
  for(const name of ['20260917124608_criminal_law_ox.sql','20260917124623_criminal_law_ox_members.sql','20260920114238_ox_progressive_loading.sql','20260921113944_ox_book_access.sql','20260922044735_ox_member_cohort_filter.sql','20260922044751_ox_device_policy.sql','20260922044806_ox_verified_purchase_required.sql','20260922044821_ox_bulk_access_grants.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+name,'utf8'));
  await core('admin_import',{collections:books.map((id,i)=>({id,sort_order:i})),chapters:books.map((id,i)=>({id:'c'+i,collection_id:id,sort_order:i})),questions:books.map((id,i)=>({id:'q'+i,chapter_id:'c'+i,prompt:'질문'+i,context:'',correct_answer:'O',explanation_html:'해설',source_question_number:String(i),reviewed:true,status:'published'}))});
  await core('admin_enabled',{enabled:true});for(const id of ['s0','s1','s2','online','lecture'])await register(id);
  await core('admin_member_set',{memberId:'s2',allowed:false});
  await db.exec('set role service_role');
  const first=(await preview()).batchId;
  const detail=await grant('detail',{batchId:first});assert.equal(detail.batch.target_count,35);assert.equal(detail.items.length,30);assert.equal((await grant('detail',{batchId:first,page:1})).items.length,5);
  assert.equal((await learn('status','s0')).enabled,false,'Preview grants no access');
  await assert.rejects(rpc('ox_grant_admin','admin_grant_issue',student('s0'),{batchId:first}),/forbidden/);
  await assert.rejects(rpc('ox_grant_admin','admin_grant_issue',{type:'admin',id:'other'},{batchId:first}),/grant_unavailable/);
  assert.equal((await grant('issue',{batchId:first})).count,35);await grant('issue',{batchId:first});
  assert.equal((await grant('list')).total,1,'Retry never duplicates a grant');
  for(const id of ['online','lecture'])assert.equal((await learn('status',id)).enabled,false,'Other categories remain purchase-gated');
  assert.equal((await learn('status','s2')).enabled,false,'Explicit whole-account suspension is preserved');
  await core('admin_member_set',{memberId:'s2',allowed:true,revision:1});assert.equal((await learn('status','s2')).enabled,true);
  const session=(await learn('device_start','s0')).sessionId;
  for(const summaryOnly of [false,true])assert.equal((await learn('bootstrap','s0',{sessionId:session,summaryOnly})).catalog.chapters.length,3);
  await learn('submit','s0',{sessionId:session,questionId:'q1',version:1,answer:'X',submissionId:crypto.randomUUID()});
  await learn('note','s0',{sessionId:session,questionId:'q1',version:1,memo:'이용권 학습 메모'});
  assert.equal((await learn('questions','s0',{sessionId:session,questions:[{id:'q1',version:1}]})).questions.length,1);
  assert.equal((await learn('detail','s0',{sessionId:session,questionId:'q1',version:1})).ok,true);
  assert.equal((await db.query("select count(*)::int n from ox_book_access")).rows[0].n,0,'Benefits never create fake purchases');
  await core('admin_book_set',{memberId:'s0',collectionIds:[books[0]],active:true,revision:0,purchaseDate:'2026-01-01',reason:'교재 구매'});
  await core('admin_book_set',{memberId:'s0',collectionIds:[books[0]],active:false,revision:1,reason:'구매 취소'});
  assert.equal((await learn('bootstrap','s0',{sessionId:session})).catalog.chapters.length,3,'Purchase cancellation does not revoke the separate benefit');
  await core('admin_book_set',{memberId:'s0',collectionIds:[books[0]],active:true,revision:2,purchaseDate:'2026-01-01',reason:'다시 구매'});
  const second=(await preview({collectionIds:[books[1]]})).batchId;await grant('issue',{batchId:second});
  await grant('revoke',{batchId:first,reason:'지원 종료'});await grant('revoke',{batchId:first,reason:'재시도'});
  assert.equal((await learn('bootstrap','s0',{sessionId:session})).catalog.chapters.length,2,'A different grant survives revocation');
  await grant('revoke',{batchId:second,reason:'종료'});
  assert.equal((await learn('bootstrap','s0',{sessionId:session})).catalog.chapters.length,1,'Purchased book survives all benefit revocations');
  for(const action of ['detail','submit','note','questions'])await assert.rejects(learn(action,'s0',{sessionId:session,questionId:'q1',version:1,answer:'O',submissionId:crypto.randomUUID(),questions:[{id:'q1',version:1}]}),/ox_book_required/);
  assert.equal((await learn('status','s1')).enabled,false);
  await assert.rejects(learn('device_start','s1'),/ox_book_required/);
  const stale=(await preview()).batchId;
  await db.exec('reset role');await db.exec("insert into students(id) values('new-student')");await db.exec('set role service_role');
  await assert.rejects(grant('issue',{batchId:stale}),/grant_target_changed/);
  const restored=(await preview({collectionIds:[books[1]]})).batchId;await grant('issue',{batchId:restored});
  const restoredData=await learn('bootstrap','s0',{sessionId:session});assert.equal(restoredData.progress.length,1);assert.equal(restoredData.notes[0].has_memo,true);
  const roster=await core('admin_members',{registeredOnly:true});assert.ok(roster.items.some(s=>s.grants?.length));
  await db.exec('reset role');await db.exec("insert into students(id) values('after-issue');update students set student_category='online_managed' where id='s1'");await register('after-issue');await db.exec('set role service_role');
  assert.equal((await learn('status','after-issue')).enabled,false,'No implicit grants to future enrollees');
  assert.equal((await learn('status','s1')).enabled,false,'Offline benefits stop on category change');
  await db.exec('reset role');await db.query("update ox_grant_batches set expires_on=(now() at time zone 'Asia/Seoul')::date-1 where id=$1",[restored]);await db.exec('set role service_role');
  assert.equal((await learn('bootstrap','s0',{sessionId:session})).catalog.chapters.length,1,'Expired grants do not remove purchases');
  const expired=(await preview()).batchId;await db.exec('reset role');await db.query("update ox_grant_batches set created_at=now()-interval '11 minutes' where id=$1",[expired]);await db.exec('set role service_role');
  await assert.rejects(grant('issue',{batchId:expired}),/grant_preview_expired/);
  await assert.rejects(preview({cohort:'99'}),/grant_empty_targets/);
  const legacyCohort=(await preview({cohort:'17'})).batchId;assert.equal((await grant('detail',{batchId:legacyCohort})).total,2,'Legacy ID cohort follows roster rule');
  for(const role of ['anon','authenticated']){await db.exec('reset role');await db.exec('set role '+role);await assert.rejects(grant('list'),/permission denied/);await assert.rejects(db.query('select * from ox_grant_batches'),/permission denied/);}
 }finally{await db.close();}
});
test('Grant API validates conditions and limits mutations to OX write permission',async()=>{
 const secret='grants-test';process.env.TEACHER_SESSION_SECRET=secret;const calls=[];
 const handler=createHandler({invoke:async(...args)=>{calls.push(args);return {ok:true};}});
 const request=async(body,permissions)=>{let code;await handler({method:'POST',headers:{host:'local',cookie:auth.COOKIE_NAME+'='+auth.createSessionToken(secret,{username:'qa',role:'teacher',permissions})},body},{setHeader(){},status(n){code=n;return this;},json(){}});return code;};
 const body={action:'admin_grant_preview',cohort:'18',collectionIds:books,expiresOn:null,reason:'지원'};
 assert.equal(await request(body,['criminal_ox.read']),403);assert.equal(await request(body,['criminal_ox.write']),200);
 for(const override of [{cohort:'lecture'},{collectionIds:[]},{collectionIds:[books[0],books[0]]},{expiresOn:'2026-02-31'},{reason:''}])assert.throws(()=>validate({...body,...override}),/invalid_request/);
 assert.equal(await request({action:'admin_grant_issue',batchId:crypto.randomUUID()},['criminal_ox.read']),403);
 assert.equal(await request({action:'admin_grant_revoke',batchId:crypto.randomUUID(),reason:'회수'},['criminal_ox.read']),403);
 assert.equal(await request({action:'admin_grant_list'},['criminal_ox.read']),200);
 const paths=[];await invokeLearning('admin_grant_preview',{type:'admin',id:'qa'},body,async(...args)=>{paths.push(args);return {ok:true};});assert.equal(paths[0][1],'rpc/ox_grant_admin');
});
