const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const handler = require("../api/curriculum-progress");
const root = path.resolve(__dirname, "..");
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), "utf8");
const schemaSource = read("supabase/add-curriculum-management.sql");
const appSource = read("app.js");
const adminSource = read("curriculum-admin.js");
const localServerSource = read("local-dev-server.js");
const seedSource = read("supabase/seed-curriculum-public-recruitment.sql");

assert.match(schemaSource, /create table if not exists public\.curriculum_student_lecture_progress/);
assert.match(schemaSource, /create table if not exists public\.curriculum_student_stage_progress/);
assert.match(schemaSource, /primary key \(student_id, lecture_id\)/);
assert.match(schemaSource, /primary key \(student_id, stage_id\)/);
assert.match(schemaSource, /target_tracks text\[\]/);
assert.match(schemaSource, /curriculum_subjects_target_tracks_idx/);
assert.match(schemaSource, /requires_wrap_up boolean/);
assert.match(schemaSource, /revoke all on public\.curriculum_student_stage_progress from anon, authenticated/);
assert.match(appSource, /saveCurriculumQuestProgress\("set_lecture"/);
assert.match(appSource, /saveCurriculumQuestProgress\("set_stage_task"/);
assert.match(appSource, /saveCurriculumQuestProgress\("complete_stage"/);
assert.match(adminSource, /적용 직렬/);
assert.match(localServerSource, /handleLocalCurriculumProgress/);
assert.match(seedSource, /Generated by scripts\/generate-curriculum-seed\.js/);
assert.match(seedSource, /'criminal-law'.*'경찰직 - 공채\(순경\)'/);
assert.equal((seedSource.match(/-stage-\d+',/g) || []).length >= 60, true);
assert.equal((seedSource.match(/-lecture-\d+',/g) || []).length, 267);

const filtered = handler._test.filterCatalogForTrack([
  { id: "public", targetTracks: ["경찰직 - 공채(순경)"] },
  { id: "vts", targetTracks: ["경찰직 - 해상교통관제(VTS)(순경)"] },
  { id: "all", targetTracks: ["*"] },
  { id: "none", targetTracks: [] },
], "경찰직 - 공채(순경)");
assert.deepEqual(filtered.map((subject) => subject.id), ["public", "all"]);

function createResponse() {
  return {
    headers: {},
    statusCode: 200,
    payload: null,
    setHeader(name, value) { this.headers[name] = value; },
    status(code) { this.statusCode = code; return this; },
    json(payload) { this.payload = payload; return this; },
  };
}

async function invoke(body) {
  const req = { method: "POST", body, headers: {} };
  const res = createResponse();
  await handler(req, res);
  return res;
}

function jsonResponse(payload, status = 200) {
  return { ok: status >= 200 && status < 300, status, json: async () => payload };
}

const originalFetch = global.fetch;
const originalEnv = { url: process.env.SUPABASE_URL, key: process.env.SUPABASE_SERVICE_ROLE_KEY };

(async () => {
  process.env.SUPABASE_URL = "https://example.supabase.co";
  process.env.SUPABASE_SERVICE_ROLE_KEY = "service-role-test";

  global.fetch = async (url) => {
    if (url.includes("notices?id=eq.__app_settings__")) return jsonResponse([{ body: JSON.stringify({ curriculumQuestEnabled: true }) }]);
    if (url.includes("rpc/validate_student_device")) return jsonResponse({ valid: false });
    throw new Error(`unexpected request: ${url}`);
  };
  const denied = await invoke({ action: "load", studentId: "20001", deviceToken: "bad-token" });
  assert.equal(denied.statusCode, 403);

  global.fetch = async (url) => {
    if (url.includes("notices?id=eq.__app_settings__")) return jsonResponse([{ body: JSON.stringify({ curriculumQuestEnabled: true }) }]);
    if (url.includes("rpc/validate_student_device")) return jsonResponse({ valid: true });
    if (url.includes("students?")) return jsonResponse([{ id: "20001", name: "테스트", track: "경찰직 - 공채(순경)", student_category: "lecture" }]);
    if (url.includes("curriculum_subjects?")) return jsonResponse([
      { id: "criminal-law", name: "형사법", short_name: "형사", tone: "indigo", target_tracks: ["경찰직 - 공채(순경)"], sort_order: 1, is_published: true },
      { id: "vts-law", name: "VTS 법규", short_name: "VTS", tone: "teal", target_tracks: ["경찰직 - 해상교통관제(VTS)(순경)"], sort_order: 2, is_published: true },
    ]);
    if (url.includes("curriculum_stages?")) return jsonResponse([
      { id: "criminal-law-stage-1", subject_id: "criminal-law", stage_number: 1, title: "오리엔테이션", sort_order: 1, is_published: true, requires_wrap_up: false },
      { id: "vts-law-stage-1", subject_id: "vts-law", stage_number: 1, title: "오리엔테이션", sort_order: 1, is_published: true, requires_wrap_up: false },
    ]);
    if (url.includes("curriculum_lectures?")) return jsonResponse([
      { id: "lecture-1", stage_id: "criminal-law-stage-1", lecture_number: "0강", title: "OT", sort_order: 1 },
      { id: "lecture-2", stage_id: "vts-law-stage-1", lecture_number: "0강", title: "OT", sort_order: 1 },
    ]);
    if (url.includes("curriculum_student_lecture_progress?")) return jsonResponse([{ lecture_id: "lecture-1", completed_at: new Date().toISOString() }]);
    if (url.includes("curriculum_student_stage_progress?")) return jsonResponse([{ stage_id: "criminal-law-stage-1", consolidation_completed: false, mbt_completed: false, stage_completed_at: new Date().toISOString() }]);
    throw new Error(`unexpected request: ${url}`);
  };
  const loaded = await invoke({ action: "load", studentId: "20001", deviceToken: "valid-token", client: {} });
  assert.equal(loaded.statusCode, 200);
  assert.deepEqual(loaded.payload.subjects.map((subject) => subject.id), ["criminal-law"]);
  assert.deepEqual(loaded.payload.progress.lectureIds, ["lecture-1"]);
  assert.equal(loaded.payload.progress.stages[0].completed, true);

  console.log("curriculum progress tests passed");
})().finally(() => {
  global.fetch = originalFetch;
  if (originalEnv.url === undefined) delete process.env.SUPABASE_URL; else process.env.SUPABASE_URL = originalEnv.url;
  if (originalEnv.key === undefined) delete process.env.SUPABASE_SERVICE_ROLE_KEY; else process.env.SUPABASE_SERVICE_ROLE_KEY = originalEnv.key;
}).catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
