const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const appSource = fs.readFileSync(path.join(root, "app.js"), "utf8");
const indexSource = fs.readFileSync(path.join(root, "index.html"), "utf8");
const styleSource = fs.readFileSync(path.join(root, "styles.css"), "utf8");
const curriculumDataSource = fs.readFileSync(path.join(root, "curriculum-data.js"), "utf8");

assert.match(appSource, /curriculum: \(\) => isCurriculumQuestEnabled\(\) \? requireStudentAuth\(renderCurriculumQuest\) : requireStudentAuth\(renderStudentHome\)/);
assert.match(appSource, /name: "형사법"[\s\S]*?totalStages: 27/);
assert.match(appSource, /name: "해양경찰학개론"[\s\S]*?totalStages: 19/);
assert.match(appSource, /name: "해사법규"[\s\S]*?totalStages: 14/);
assert.match(appSource, /형법 1~18단계 · 형사소송법 19~27단계/);
assert.match(appSource, /"이론강의"/);
assert.match(appSource, /label: "단권화 작업"/);
assert.match(appSource, /label: "MBT 풀이"/);
assert.match(appSource, /function getCurriculumStageLectures/);
assert.match(appSource, /function isCurriculumOrientationStage/);
assert.match(appSource, /curriculum-lecture-row/);
assert.match(appSource, /currentLectureCount.*lectureCount.*강/s);
assert.match(appSource, /모든 강의와 단권화, MBT를 체크하면 다음 단계가 열립니다/);
assert.match(appSource, /오리엔테이션 강의를 체크하면 다음 단계가 열립니다/);
assert.match(appSource, /orientationStage \? null : el\("section", \{ className: "curriculum-after-lecture-section"/);
assert.doesNotMatch(appSource, /curriculum[^\n]*(?:총 영상|목표 점수|사진 제출)/);
assert.doesNotMatch(indexSource, /curriculum: "커리큘럼 퀘스트"/);
assert.doesNotMatch(indexSource, /curriculum-data\.js/);
assert.doesNotMatch(indexSource, /route === "curriculum"/);
assert.match(appSource, /normalized === "curriculum" && !isCurriculumQuestEnabled\(\)/);
assert.match(appSource, /curriculum: \(\) => isCurriculumQuestEnabled\(\)/);
assert.doesNotMatch(appSource, /현재 이용할 수 없는 기능입니다/);
assert.match(curriculumDataSource, /"criminal-law"/);
assert.match(curriculumDataSource, /"26강"/);
assert.match(curriculumDataSource, /"정범과 공범의 일반이론"/);
assert.match(styleSource, /\.curriculum-stage-card\.current/);
assert.match(styleSource, /\.curriculum-finish-task\.completed/);
assert.match(styleSource, /\.curriculum-lecture-row\.completed/);
assert.match(styleSource, /\.student-curriculum-page\s*\{[^}]*max-width: 420px/);
assert.match(styleSource, /\.curriculum-page-head\s*\{[^}]*#062b5f/);
assert.match(appSource, /curriculum-content-sheet/);
assert.match(appSource, /curriculum-stage-meta/);
assert.match(appSource, /curriculum-phase-label/);
assert.match(appSource, /curriculum-detail-navy/);
assert.match(styleSource, /\.curriculum-content-sheet\s*\{[^}]*border-radius: 28px 28px 0 0/);
assert.match(styleSource, /\.curriculum-stage-card\.current\s*\{[^}]*linear-gradient/);
assert.match(styleSource, /\.curriculum-stage-status\.current/);
assert.match(styleSource, /\.curriculum-detail-navy\s*\{[^}]*#062b5f/);

console.log("curriculum quest UI tests passed");
