const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const styles = fs.readFileSync(path.join(root, "styles.css"), "utf8");

assert.match(app, /fetch\("\/api\/study-cafe-rooms"/);
assert.match(app, /function requestStudyRoomPreviewAction\(action, payload = \{\}\)/);
assert.match(app, /function openStudyRoomListModal\(\)/);
assert.match(app, /ariaLabel: "스터디방 목록 열기"/);
assert.match(app, /el\("span", \{\}, "스터디방 목록"\)/);
assert.match(app, /className: "study-cafe-room-label-row"[\s\S]*?className: "study-room-open-button"/);
assert.match(app, /function openStudyRoomCreateModal\(\)/);
assert.match(app, /mutateStudyRoom\("create", \{[\s\S]*?theme: "oak"/);
assert.match(app, /field\("방 색상 테마", themeSelect\)/);
assert.match(app, /theme: themeSelect\.value/);
assert.match(app, /Array\.from\(\{ length: 19 \}, \(_, index\) => String\(index \+ 2\)\)/);
assert.match(app, /option\.textContent = `\$\{option\.value\}좌석`/);
assert.match(app, /function openStudyRoomJoinModal\(room\)/);
assert.match(app, /function renderStudentPrivateStudyRoom\(student\)/);
assert.match(app, /function renderPrivateStudyRoomSeat\(seatNumber, room, student\)/);
assert.match(app, /function openPrivateStudyRoomSeatMoveModal\(currentSeatNumber, nextSeatNumber, room\)/);
assert.match(app, /현재 과목과 공부시간은 그대로 유지됩니다/);
assert.match(app, /notify\(`\$\{nextSeatNumber\}번 좌석으로 이동했습니다.`\)/);
assert.match(app, /className: `study-cafe-seat study-room-seat/);
assert.match(app, /className: `study-cafe-room theme-\$\{roomTheme\} study-private-room`/);
assert.match(app, /renderStudyCafeSeatedVisual\(occupant\.tone \|\| "blue", false/);
assert.match(app, /showWritingArms: true/);
assert.match(app, /"data-study-member-time": isMine/);
assert.match(app, /"data-study-base-seconds": String\(Number\(occupant\.todaySeconds\) \|\| 0\)/);
assert.match(app, /const rankingRoomSeat =\s*seatNumber > 0 &&\s*getStudyCafeRoomIndexForSeat\(seatNumber\)/);
assert.match(app, /openStudyCafeMemberModal\(\{/);
assert.doesNotMatch(app, /function openPrivateStudyRoomMemberModal/);
assert.match(app, /function renderStudyRoomChat\(room\)/);
assert.match(app, /function renderStudyRoomChatBody\(room, messages\)/);
assert.match(app, /maxlength: "300"/);
assert.match(app, /event\.key === "Enter" && !event\.shiftKey/);
assert.match(app, /mutateStudyRoom\("message_delete"/);
assert.match(app, /mutateStudyRoom\("kick"/);
assert.match(app, /mutateStudyRoom\("close"/);
assert.match(app, /button\("방 삭제", "btn danger study-room-close-button"/);
assert.match(app, /방 목록에서도 사라집니다/);
assert.match(app, /room\.role === "host"/);
assert.match(styles, /\.study-private-seat-grid/);
assert.match(styles, /\.study-room-chat\.expanded \.study-room-chat-log/);
assert.match(styles, /\.study-room-chat\.collapsed/);
assert.match(styles, /@media \(max-width: 520px\)/);

console.log("study room UI tests passed");
