const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const styles = fs.readFileSync(path.join(root, "styles.css"), "utf8");

assert.match(app, /fetch\("\/api\/study-cafe-rooms"/);
assert.match(app, /function requestStudyRoomPreviewAction\(action, payload = \{\}\)/);
assert.match(app, /function openStudyRoomListModal\(\)/);
assert.match(app, /ariaLabel: "스터디방 목록 열기"/);
assert.match(app, /el\("span", \{\}, "스터디방 목록"\)/);
assert.match(app, /className: `study-cafe-room-label-row[\s\S]*?className: "study-room-open-button"/);
assert.match(app, /function openStudyRoomCreateModal\(\)/);
assert.match(app, /mutateStudyRoom\("create", \{[\s\S]*?theme: "oak"/);
assert.match(app, /field\("방 색상 테마", themeSelect\)/);
assert.match(app, /theme: themeSelect\.value/);
assert.match(app, /Array\.from\(\{ length: 19 \}, \(_, index\) => String\(index \+ 2\)\)/);
assert.match(app, /option\.textContent = `\$\{option\.value\}좌석`/);
assert.match(app, /function openStudyRoomJoinModal\(room\)/);
assert.match(app, /function renderStudentPrivateStudyRoom\(student\)/);
assert.match(app, /className: "study-private-room-overview"[\s\S]*?"좌석 현황"[\s\S]*?className: "study-private-room-members-link"[\s\S]*?onclick: openStudyRoomMembersModal/);
assert.match(
  app,
  /className: "study-cafe-seat-grid study-private-seat-grid"[\s\S]*?className: "study-private-seat-guide"[\s\S]*?"이용할 좌석을 선택해주세요"[\s\S]*?renderStudyRoomChat\(room\)/
);
assert.match(app, /ariaLabel: `멤버 목록 열기, 현재 \$\{room\.members\.length\}명, 정원 \$\{room\.capacity\}명`/);
assert.match(app, /textContent: `멤버 \$\{room\.members\.length\}\/\$\{room\.capacity\} 보기`/);
assert.doesNotMatch(app, /button\("멤버 목록", "study-room-members-button"/);
assert.doesNotMatch(app, /className: "study-private-room-count"/);
assert.doesNotMatch(app, /study-private-room-members-arrow/);
assert.match(app, /function openStudyRoomMembersModal\(\)/);
assert.match(app, /title: `멤버 목록 · \$\{room\.members\.length\}명`/);
assert.match(app, /member\.role === "host"/);
assert.match(app, /member\.seatNumber \? `\$\{member\.seatNumber\}번 좌석` : "좌석 미선택"/);
assert.match(app, /const canViewDetails = !member\.isMine && Boolean\(member\.seatNumber\)/);
assert.match(app, /canViewDetails \? "button" : "article"/);
assert.match(app, /ariaLabel: `\$\{member\.name\}님 상세 보기`/);
assert.match(app, /className: "study-room-members-item-arrow"/);
assert.doesNotMatch(app, /study-room-member-detail-button/);
assert.match(app, /function renderPrivateStudyRoomSeat\(seatNumber, room, student\)/);
assert.match(app, /function openPrivateStudyRoomSeatMoveModal\(currentSeatNumber, nextSeatNumber, room\)/);
assert.match(app, /현재 과목과 공부시간은 그대로 유지됩니다/);
assert.match(app, /notify\(`\$\{nextSeatNumber\}번 좌석으로 이동했습니다.`\)/);
assert.match(app, /className: `study-cafe-seat study-room-seat/);
assert.match(app, /className: `study-cafe-room theme-\$\{roomTheme\} study-private-room`/);
assert.match(app, /renderStudyCafeSeatedVisual\(occupant\.tone \|\| "blue", false/);
assert.match(app, /showWritingArms: true/);
assert.match(app, /"data-study-member-time": isMine/);
assert.match(app, /"data-study-base-seconds": String\(Number\(occupant\.todaySeconds\) \|\| 0\)/);
assert.match(app, /const rankingRoomSeat =\s*seatNumber > 0 &&\s*getStudyCafeRoomIndexForSeat\(seatNumber\)/);
assert.match(app, /openStudyCafeMemberModal\(\{/);
assert.doesNotMatch(app, /function openPrivateStudyRoomMemberModal/);
assert.match(app, /function renderStudyRoomChat\(room\)/);
assert.match(app, /function renderStudyRoomChatBody\(room, messages\)/);
assert.match(app, /maxlength: "300"/);
assert.match(app, /event\.key === "Enter" && !event\.shiftKey/);
assert.match(app, /mutateStudyRoom\("message_delete"/);
assert.match(app, /mutateStudyRoom\("kick"/);
assert.match(app, /mutateStudyRoom\("close"/);
assert.match(app, /button\("방 삭제", "btn danger study-room-close-button"/);
assert.match(app, /방 목록에서도 사라집니다/);
assert.match(app, /room\.role === "host"/);
assert.match(app, /className: "study-room-host-label" \}, "\(방장\)"/);
assert.doesNotMatch(app, /className: "study-room-host-chip"/);
assert.doesNotMatch(app, /"👑 방장"/);
assert.match(app, /button\("전체 카페 보기", "study-room-cafe-button", "button", browsePublicStudyCafe\)/);
assert.match(app, /button\("방 메뉴", "study-room-menu-button", "button", openStudyRoomOptionsModal\)/);
assert.match(app, /function browsePublicStudyCafe\(\)/);
assert.match(app, /function returnToOwnStudyRoom\(\)/);
assert.match(app, /function openStudyRoomOptionsModal\(\)/);
assert.match(app, /button\("스터디룸 탈퇴", "btn danger study-room-withdraw-button"/);
assert.match(app, /button\("내 스터디룸", "study-room-return-button", "button", returnToOwnStudyRoom\)/);
assert.match(app, /readOnly: browsingPublicCafe/);
assert.match(app, /\? "전체 카페 둘러보는 중"/);
assert.match(app, /if \(!occupant && readOnly\) \{[\s\S]*?전체 카페에서는 좌석 현황만 볼 수 있어요\. 좌석은 내 스터디룸에서 선택해주세요/);
assert.doesNotMatch(app, /disabled: readOnly && !occupant/);
assert.doesNotMatch(app, /button\("나가기", "study-room-leave-button", "button", leaveCurrentStudyRoom\)/);
assert.match(app, /방장은 \$\{nextHost\.name\}님에게 자동으로 위임됩니다/);
assert.match(app, /if \(!room \|\| room\.role !== "host"\)/);
assert.match(app, /방장만 방 설정을 변경할 수 있습니다/);
assert.match(styles, /\.study-room-host-label/);
assert.doesNotMatch(styles, /\.study-room-host-chip/);
assert.match(styles, /\.study-room-options-content/);
assert.match(styles, /\.study-room-browse-guide/);
assert.match(styles, /\.study-room-members-list/);
assert.match(styles, /\.study-room-members-item/);
assert.match(styles, /\.study-room-members-item\.is-clickable/);
assert.doesNotMatch(styles, /\.study-room-member-detail-button/);
assert.match(styles, /\.study-private-room-members-link/);
assert.match(styles, /\.study-private-room-overview/);
assert.match(styles, /\.study-private-my-actions\s*\{[^}]*width: 104px[^}]*grid-template-columns: 1fr/);
assert.match(styles, /\.study-private-my-actions \.study-room-subject-button,[\s\S]*?\.study-private-my-actions \.study-private-release-button\s*\{[^}]*width: 100%[^}]*min-height: 38px/);
assert.match(styles, /\.study-private-seat-grid/);
assert.match(styles, /\.study-room-chat\.expanded \.study-room-chat-log/);
assert.match(styles, /\.study-room-chat\.collapsed/);
assert.match(styles, /@media \(max-width: 520px\)/);

console.log("study room UI tests passed");
