const assert = require("node:assert/strict");
const fs = require("node:fs");

const appSource = fs.readFileSync("app.js", "utf8");
const sharedSource = fs.readFileSync("shared.js", "utf8");
const teacherSource = fs.readFileSync("teacher.js", "utf8");
const teacherHtml = fs.readFileSync("teacher.html", "utf8");
const styleSource = fs.readFileSync("styles.css", "utf8");
const authSource = fs.readFileSync("api/teacher-auth-utils.js", "utf8");

assert.match(teacherHtml, /data-route="study-cafe-admin">온라인 스터디카페/);
assert.match(appSource, /"study-cafe-admin": "온라인 스터디카페"/);
assert.match(appSource, /"study-cafe-admin": renderStudyCafeAdmin/);
assert.match(appSource, /hasTeacherPermission\("study_cafe\.read"\) \? moduleCard\("온라인 스터디카페"/);
assert.match(sharedSource, /"study-cafe-admin": "study_cafe\.read"/);
const managerPermissions = authSource.match(/const STUDENT_MANAGER_PERMISSIONS = \[([\s\S]*?)\];/)?.[1] || "";
assert.doesNotMatch(managerPermissions, /study_cafe\.(?:read|write)/);
assert.match(teacherSource, /function renderStudyCafeAdmin\(\)/);
assert.match(teacherSource, /fetch\("\/api\/study-cafe-admin"/);
assert.match(teacherSource, /renderStudyCafeAdminActionButton\("타이머 종료", "mini-btn", "stop_session", member\)/);
assert.match(teacherSource, /renderStudyCafeAdminActionButton\("좌석 비우기", "mini-btn danger", "release_seat", member\)/);
assert.match(teacherSource, /function renderStudyCafeAdminActionButton\(label, className, action, member\)/);
assert.match(teacherSource, /active_session_not_found/);
assert.match(teacherSource, /seat_not_found/);
assert.match(teacherSource, /studyCafeAdminState\.refreshTimer = window\.setInterval/);
assert.match(teacherSource, /STUDY_CAFE_ADMIN_SAFETY_REFRESH_INTERVAL_MS = 60 \* 1000/);
assert.match(teacherSource, /document\.visibilityState !== "hidden"/);
assert.match(teacherSource, /document\.addEventListener\("visibilitychange", refreshWhenActive\)/);
assert.match(teacherSource, /\.on\("broadcast", \{ event: "state-changed" \}, scheduleStudyCafeAdminRealtimeRefresh\)/);
assert.match(teacherSource, /\.on\("broadcast", \{ event: "room-changed" \}, scheduleStudyCafeAdminRealtimeRefresh\)/);
assert.doesNotMatch(teacherSource, /\["랭킹 열람실", "A 열람실", "B 열람실", "C 열람실"\]/);
assert.match(teacherSource, /ariaLabel: "스터디카페 열람실 선택"/);
assert.match(teacherSource, /activeRoomIndex: 0/);
assert.match(teacherSource, /STUDY_CAFE_ROOMS\.length - 1/);
assert.match(teacherSource, /STUDY_CAFE_ROOMS\.map\(\(room, roomIndex\)/);
assert.match(teacherSource, /room\.endSeat - room\.startSeat \+ 1/);
assert.match(teacherSource, /className: "study-cafe-admin-room-tabs"/);
assert.match(teacherSource, /function buildStudyCafeAdminPublicRoomEntries\(roomIndex, members\)/);
assert.match(teacherSource, /rankedMembers = \[\.\.\.roomMembers\]\.sort\(sortStudyCafeAdminRankingMembers\)/);
assert.match(teacherSource, /Number\(right\.todaySeconds\)[\s\S]*?Number\(left\.seatNumber\) - Number\(right\.seatNumber\)/);
assert.match(teacherSource, /displaySeatLabel: String\(index \+ 1\)/);
assert.match(teacherSource, /data-study-cafe-physical-seat-number/);
assert.match(teacherSource, /return rank \? `\$\{room\.label\} \$\{rank\}위` : room\.label/);
assert.match(teacherSource, /지원 종료 좌석/);
assert.match(teacherSource, /renderStudyCafeAdminStat\("좌석 배정"/);
assert.match(teacherSource, /summary\.connectedSeatedCount/);
assert.match(teacherSource, /summary\.disconnectedSeatedCount/);
assert.match(teacherSource, /function renderStudyCafeAdminPrivateRooms\(rooms, members, canWrite\)/);
assert.match(teacherSource, /activePrivateRoomId: ""/);
assert.match(teacherSource, /className: "study-cafe-admin-private-room-tabs"/);
assert.match(teacherSource, /formatStudyCafeAdminMemberLocation\(member\)/);
assert.match(teacherSource, /role: "tablist"/);
assert.match(teacherSource, /role: "tabpanel"/);
assert.match(styleSource, /\.study-cafe-admin-seat-grid\s*\{[^}]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/);
assert.match(styleSource, /\.study-cafe-admin-seat-grid/);
assert.match(styleSource, /\.study-cafe-admin-room-tabs/);
assert.match(styleSource, /\.study-cafe-admin-room-tab\.active/);
assert.match(styleSource, /\.study-cafe-admin-private-room-tabs/);
assert.match(styleSource, /\.study-cafe-admin-seat-grid\.private/);
assert.match(styleSource, /\.study-cafe-admin-member-list/);
assert.match(styleSource, /\.study-cafe-admin-status\.running/);
assert.match(teacherSource, /function renderStudyCafeAdminHistory\(\)/);
assert.match(teacherSource, /action: "history"/);
assert.match(teacherSource, /const startDate = history\.startDate/);
assert.match(teacherSource, /const endDate = history\.endDate/);
assert.match(teacherSource, /function renderStudyCafeAdminHistoryDetail\(student\)/);
assert.match(teacherSource, /students\.flatMap\(\(student\) =>/);
assert.match(teacherSource, /className: "study-cafe-admin-history-inline-detail"/);
assert.doesNotMatch(teacherSource, /selectedStudent \? renderStudyCafeAdminHistorySelection\(selectedStudent\) : null/);
assert.match(teacherSource, /formatStudyCafeAdminHistoryTime\(session\.startedAt\)/);
assert.match(teacherSource, /formatStudyCafeAdminHistoryEnd\(session, day\.date\)/);
assert.match(teacherSource, /action: "history_detail"/);
assert.match(teacherSource, /function loadStudyCafeAdminHistoryDetail\(student\)/);
assert.match(teacherSource, /history\.data = null/);
assert.match(teacherSource, /history\.loaded = true/);
assert.match(teacherSource, /await resetStudyCafeAdminStateAfterLogout\(\)/);
assert.match(teacherSource, /function resetStudyCafeAdminStateAfterLogout\(\)/);
assert.match(teacherSource, /teacherAuth\.authenticated && currentRoute === "study-cafe-admin"/);
assert.match(teacherSource, /function downloadStudyCafeAdminHistoryWorkbook\(\)/);
assert.match(teacherSource, /createStudentCohortWorkbookBlob\("순공시간 조회", rows\)/);
assert.match(styleSource, /\.study-cafe-admin-history-filters/);
assert.match(styleSource, /\.study-cafe-admin-history-row/);
assert.match(styleSource, /\.study-cafe-admin-history-inline-detail/);
assert.match(styleSource, /\.study-cafe-admin-history-detail/);

console.log("study-cafe-admin-ui tests passed");
